In [ ]:
from google.colab import files

uploaded = files.upload()

Saving AR_AP_Analytics_Dashboard.xlsx to AR_AP_Analytics_Dashboard.xlsx

In [ ]:
import pandas as pd

file_path = "/content/AR_AP_Analytics_Dashboard.xlsx"

excel_file = pd.ExcelFile(file_path)

print("=" * 80)
print("AR/AP SOURCE WORKBOOK CONTROL")
print("=" * 80)

print(f"File: {file_path}")
print(f"Sheets found: {len(excel_file.sheet_names)}")

print("\nSheet Names:")
for i, sheet in enumerate(excel_file.sheet_names, start=1):
    print(f"{i}. {sheet}")

print("\nSOURCE WORKBOOK: PASS ✓")
print("=" * 80)

================================================================================
AR/AP SOURCE WORKBOOK CONTROL
================================================================================
File: /content/AR_AP_Analytics_Dashboard.xlsx
Sheets found: 13

Sheet Names:
1. Customers Master
2. Suppliers Master
3. Sales Transactions
4. Purchase Transactions
5. Customer Receipts
6. Supplier Payments
7. Chart of Accounts
8. Calendar
9. Trial Balance
10. Income Statement
11. Balance Sheet
12. Cash Flow
13. Customer Mapping

SOURCE WORKBOOK: PASS ✓
================================================================================

### Step 10.05 Part 1: Source Data Load & Data Model Control

In [ ]:
# ============================================================
# STEP 10.5 — PART 1
# SOURCE DATA LOAD & DATA MODEL CONTROL
# ============================================================

import pandas as pd

SOURCE_FILE = "/content/AR_AP_Analytics_Dashboard.xlsx"

# ------------------------------------------------------------
# Load Source Tables
# ------------------------------------------------------------

df_customers = pd.read_excel(
    SOURCE_FILE,
    sheet_name="Customers Master"
)

df_suppliers = pd.read_excel(
    SOURCE_FILE,
    sheet_name="Suppliers Master"
)

df_sales = pd.read_excel(
    SOURCE_FILE,
    sheet_name="Sales Transactions"
)

df_purchases = pd.read_excel(
    SOURCE_FILE,
    sheet_name="Purchase Transactions"
)

df_customer_receipts = pd.read_excel(
    SOURCE_FILE,
    sheet_name="Customer Receipts"
)

df_supplier_payments = pd.read_excel(
    SOURCE_FILE,
    sheet_name="Supplier Payments"
)

df_coa = pd.read_excel(
    SOURCE_FILE,
    sheet_name="Chart of Accounts"
)

df_calendar = pd.read_excel(
    SOURCE_FILE,
    sheet_name="Calendar"
)

# ------------------------------------------------------------
# Data Model Control
# ------------------------------------------------------------

tables = {
    "Customers Master": df_customers,
    "Suppliers Master": df_suppliers,
    "Sales Transactions": df_sales,
    "Purchase Transactions": df_purchases,
    "Customer Receipts": df_customer_receipts,
    "Supplier Payments": df_supplier_payments,
    "Chart of Accounts": df_coa,
    "Calendar": df_calendar
}

print("=" * 80)
print("STEP 10.5 — PART 1")
print("SOURCE DATA LOAD & DATA MODEL CONTROL")
print("=" * 80)

print(f"\nSource File: {SOURCE_FILE}")
print(f"Tables Loaded: {len(tables)}")

print("\n" + "-" * 80)
print("TABLE STRUCTURE")
print("-" * 80)

for table_name, df in tables.items():

    print(
        f"{table_name:<25} | "
        f"Rows: {len(df):>5} | "
        f"Columns: {len(df.columns):>3}"
    )

print("\n" + "-" * 80)
print("DATA MODEL CONTROL")
print("-" * 80)

all_loaded = all(df is not None for df in tables.values())

if all_loaded and len(tables) == 8:
    print("All 8 source tables loaded successfully.")
    print("SOURCE DATA LOAD: PASS ✓")
else:
    print("SOURCE DATA LOAD: FAIL ✗")

print("=" * 80)

================================================================================
STEP 10.5 — PART 1
SOURCE DATA LOAD & DATA MODEL CONTROL
================================================================================

Source File: /content/AR_AP_Analytics_Dashboard.xlsx
Tables Loaded: 8

--------------------------------------------------------------------------------
TABLE STRUCTURE
--------------------------------------------------------------------------------
Customers Master          | Rows:    20 | Columns:   9
Suppliers Master          | Rows:    15 | Columns:   7
Sales Transactions        | Rows:    15 | Columns:  22
Purchase Transactions     | Rows:    15 | Columns:  12
Customer Receipts         | Rows:    10 | Columns:  10
Supplier Payments         | Rows:    10 | Columns:  10
Chart of Accounts         | Rows:    22 | Columns:   7
Calendar                  | Rows:     0 | Columns:  10

--------------------------------------------------------------------------------
DATA MODEL CONTROL
--------------------------------------------------------------------------------
All 8 source tables loaded successfully.
SOURCE DATA LOAD: PASS ✓
================================================================================

### Step 10.05 Part 2: Column Structure Data Type Validation

In [ ]:
# ============================================================
# STEP 10.5 — PART 2
# COLUMN STRUCTURE & DATA TYPE VALIDATION
# ============================================================

print("=" * 80)
print("STEP 10.5 — PART 2")
print("COLUMN STRUCTURE & DATA TYPE VALIDATION")
print("=" * 80)

for table_name, df in tables.items():

    print("\n" + "-" * 80)
    print(f"{table_name}")
    print("-" * 80)

    print(f"Rows: {len(df)}")
    print(f"Columns: {len(df.columns)}")

    print("\nColumn Names:")
    for col in df.columns:
        print(f"   - {col}")

    print("\nData Types:")
    print(df.dtypes.to_string())

print("\n" + "=" * 80)
print("PART 2 VALIDATION COMPLETED")
print("=" * 80)

================================================================================
STEP 10.5 — PART 2
COLUMN STRUCTURE & DATA TYPE VALIDATION
================================================================================

--------------------------------------------------------------------------------
Customers Master
--------------------------------------------------------------------------------
Rows: 20
Columns: 9

Column Names:
   - Customer ID
   - Customer Name
   - Customer Type
   - City
   - Country
   - Credit Limit
   - Payment Terms
   - SalesPerson
   - Status

Data Types:
Customer ID      object
Customer Name    object
Customer Type    object
City             object
Country          object
Credit Limit      int64
Payment Terms    object
SalesPerson      object
Status           object

--------------------------------------------------------------------------------
Suppliers Master
--------------------------------------------------------------------------------
Rows: 15
Columns: 7

Column Names:
   - Suppliers ID
   - Suppliers Name
   - Suppliers Category
   - City
   - Country
   - Payment Terms
   - Status

Data Types:
Suppliers ID          object
Suppliers Name        object
Suppliers Category    object
City                  object
Country               object
Payment Terms         object
Status                object

--------------------------------------------------------------------------------
Sales Transactions
--------------------------------------------------------------------------------
Rows: 15
Columns: 22

Column Names:
   - Invoice No
   - Invoice Date
   - Customer ID
   - Customer  Name
   - Purchase  Category
   - Invoice Amount
   - Cost
   - Discount
   - VAT
   - Total Amount
   - Due Date
   - Payment Terms
   - Status
   - City
   - Country
   - SalesPerson
   - Product
   - Quantity
   - Unit Price
   - Cost Amount
   - Gross Profit
   - Payment Type

Data Types:
Invoice No                    object
Invoice Date          datetime64[ns]
Customer ID                   object
Customer  Name                object
Purchase  Category            object
Invoice Amount                 int64
Cost                         float64
Discount                       int64
VAT                            int64
Total Amount                   int64
Due Date              datetime64[ns]
Payment Terms                 object
Status                        object
City                          object
Country                       object
SalesPerson                   object
Product                       object
Quantity                       int64
Unit Price                     int64
Cost Amount                  float64
Gross Profit                 float64
Payment Type                  object

--------------------------------------------------------------------------------
Purchase Transactions
--------------------------------------------------------------------------------
Rows: 15
Columns: 12

Column Names:
   - Invoice No
   - Invoice Date
   - Suppliers ID
   - Suppliers  Name
   - Purchase  Category
   - Invoice Amount
   - Discount
   - VAT
   - Total Amount
   - Due Date
   - Payment Terms
   - Status

Data Types:
Invoice No                    object
Invoice Date          datetime64[ns]
Suppliers ID                  object
Suppliers  Name               object
Purchase  Category            object
Invoice Amount                 int64
Discount                       int64
VAT                            int64
Total Amount                   int64
Due Date              datetime64[ns]
Payment Terms                 object
Status                        object

--------------------------------------------------------------------------------
Customer Receipts
--------------------------------------------------------------------------------
Rows: 10
Columns: 10

Column Names:
   - Receipt No
   - Receipt Date
   - Customer ID
   - Customer  Name
   - Invoice No
   - Amount Received
   - Payment Method
   - Bank Account
   - Reference No
   - Status

Data Types:
Receipt No                 object
Receipt Date       datetime64[ns]
Customer ID                object
Customer  Name             object
Invoice No                 object
Amount Received             int64
Payment Method             object
Bank Account               object
Reference No               object
Status                     object

--------------------------------------------------------------------------------
Supplier Payments
--------------------------------------------------------------------------------
Rows: 10
Columns: 10

Column Names:
   - Payment No
   - Payment Date
   - Supplier ID
   - Supplier Name
   - Invoice No
   - Amount Paid
   - Payment Method
   - Bank Account
   - Reference No
   - Status

Data Types:
Payment No                object
Payment Date      datetime64[ns]
Supplier ID               object
Supplier Name             object
Invoice No                object
Amount Paid                int64
Payment Method            object
Bank Account              object
Reference No              object
Status                    object

--------------------------------------------------------------------------------
Chart of Accounts
--------------------------------------------------------------------------------
Rows: 22
Columns: 7

Column Names:
   - Account Code
   - Account Name
   - Account Type
   - Accounts Category
   - Normal Balance
   - Parent Account
   - Status

Data Types:
Account Code          int64
Account Name         object
Account Type         object
Accounts Category    object
Normal Balance       object
Parent Account       object
Status               object

--------------------------------------------------------------------------------
Calendar
--------------------------------------------------------------------------------
Rows: 0
Columns: 10

Column Names:
   - Date
   - Year
   - Quarter
   - Quarter No
   - Month No
   - Month Name
   - Month - Year
   - Week No
   - Day
   - Day Name

Data Types:
Date            object
Year            object
Quarter         object
Quarter No      object
Month No        object
Month Name      object
Month - Year    object
Week No         object
Day             object
Day Name        object

================================================================================
PART 2 VALIDATION COMPLETED
================================================================================

### Step 10.05 Part 3: Calender Table Validation & Rebuild

In [ ]:
# ============================================================
# STEP 10.5 — PART 3
# CALENDAR TABLE VALIDATION & REBUILD
# ============================================================

print("=" * 80)
print("STEP 10.5 — PART 3")
print("CALENDAR TABLE VALIDATION & REBUILD")
print("=" * 80)

# ------------------------------------------------------------
# Collect all relevant transaction dates
# ------------------------------------------------------------

date_series = pd.concat([
    df_sales["Invoice Date"],
    df_sales["Due Date"],
    df_purchases["Invoice Date"],
    df_purchases["Due Date"],
    df_customer_receipts["Receipt Date"],
    df_supplier_payments["Payment Date"]
]).dropna()

min_date = pd.to_datetime(date_series).min()
max_date = pd.to_datetime(date_series).max()

print(f"\nMinimum Transaction Date : {min_date.date()}")
print(f"Maximum Transaction Date : {max_date.date()}")

# ------------------------------------------------------------
# Rebuild Calendar
# ------------------------------------------------------------

calendar_dates = pd.date_range(
    start=min_date,
    end=max_date,
    freq="D"
)

df_calendar = pd.DataFrame({
    "Date": calendar_dates
})

df_calendar["Year"] = df_calendar["Date"].dt.year
df_calendar["Quarter"] = "Q" + df_calendar["Date"].dt.quarter.astype(str)
df_calendar["Quarter No"] = df_calendar["Date"].dt.quarter
df_calendar["Month No"] = df_calendar["Date"].dt.month
df_calendar["Month Name"] = df_calendar["Date"].dt.month_name()
df_calendar["Month - Year"] = df_calendar["Date"].dt.strftime("%b-%Y")
df_calendar["Week No"] = df_calendar["Date"].dt.isocalendar().week.astype(int)
df_calendar["Day"] = df_calendar["Date"].dt.day
df_calendar["Day Name"] = df_calendar["Date"].dt.day_name()

# ------------------------------------------------------------
# Calendar Controls
# ------------------------------------------------------------

expected_days = (max_date - min_date).days + 1
actual_days = len(df_calendar)

duplicate_dates = df_calendar["Date"].duplicated().sum()

date_gaps = (
    df_calendar["Date"].sort_values().diff().dropna()
    != pd.Timedelta(days=1)
).sum()

print("\n" + "-" * 80)
print("CALENDAR CONTROL")
print("-" * 80)

print(f"Expected Calendar Days : {expected_days}")
print(f"Actual Calendar Days   : {actual_days}")
print(f"Duplicate Dates        : {duplicate_dates}")
print(f"Date Gaps              : {date_gaps}")

# ------------------------------------------------------------
# Final Control
# ------------------------------------------------------------

if (
    expected_days == actual_days
    and duplicate_dates == 0
    and date_gaps == 0
):
    print("\nCALENDAR TABLE: PASS ✓")
else:
    print("\nCALENDAR TABLE: FAIL ✗")

print("=" * 80)

================================================================================
STEP 10.5 — PART 3
CALENDAR TABLE VALIDATION & REBUILD
================================================================================

Minimum Transaction Date : 2026-01-02
Maximum Transaction Date : 2026-07-30

--------------------------------------------------------------------------------
CALENDAR CONTROL
--------------------------------------------------------------------------------
Expected Calendar Days : 210
Actual Calendar Days   : 210
Duplicate Dates        : 0
Date Gaps              : 0

CALENDAR TABLE: PASS ✓
================================================================================

### Step 10.05 Part 4: Master Data & Transaction Key Validation

In [ ]:
# ============================================================
# STEP 10.5 — PART 4
# MASTER DATA & TRANSACTION KEY VALIDATION
# ============================================================

print("=" * 80)
print("STEP 10.5 — PART 4")
print("MASTER DATA & TRANSACTION KEY VALIDATION")
print("=" * 80)

# ------------------------------------------------------------
# Prepare Master Keys
# ------------------------------------------------------------

customer_ids = set(
    df_customers["Customer ID"]
    .dropna()
    .astype(str)
    .str.strip()
)

supplier_ids = set(
    df_suppliers["Suppliers ID"]
    .dropna()
    .astype(str)
    .str.strip()
)

sales_invoice_ids = set(
    df_sales["Invoice No"]
    .dropna()
    .astype(str)
    .str.strip()
)

purchase_invoice_ids = set(
    df_purchases["Invoice No"]
    .dropna()
    .astype(str)
    .str.strip()
)

# ------------------------------------------------------------
# Validate Customer IDs
# ------------------------------------------------------------

sales_customer_ids = set(
    df_sales["Customer ID"]
    .dropna()
    .astype(str)
    .str.strip()
)

receipt_customer_ids = set(
    df_customer_receipts["Customer ID"]
    .dropna()
    .astype(str)
    .str.strip()
)

missing_sales_customers = sales_customer_ids - customer_ids
missing_receipt_customers = receipt_customer_ids - customer_ids

# ------------------------------------------------------------
# Validate Supplier IDs
# ------------------------------------------------------------

purchase_supplier_ids = set(
    df_purchases["Suppliers ID"]
    .dropna()
    .astype(str)
    .str.strip()
)

payment_supplier_ids = set(
    df_supplier_payments["Supplier ID"]
    .dropna()
    .astype(str)
    .str.strip()
)

missing_purchase_suppliers = purchase_supplier_ids - supplier_ids
missing_payment_suppliers = payment_supplier_ids - supplier_ids

# ------------------------------------------------------------
# Validate Invoice Numbers
# ------------------------------------------------------------

receipt_invoice_ids = set(
    df_customer_receipts["Invoice No"]
    .dropna()
    .astype(str)
    .str.strip()
)

payment_invoice_ids = set(
    df_supplier_payments["Invoice No"]
    .dropna()
    .astype(str)
    .str.strip()
)

missing_receipt_invoices = receipt_invoice_ids - sales_invoice_ids
missing_payment_invoices = payment_invoice_ids - purchase_invoice_ids

# ------------------------------------------------------------
# Print Results
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("CUSTOMER KEY CONTROL")
print("-" * 80)

print(f"Customers in Master              : {len(customer_ids)}")
print(f"Customers referenced in Sales    : {len(sales_customer_ids)}")
print(f"Customers referenced in Receipts : {len(receipt_customer_ids)}")
print(f"Missing Sales Customer IDs       : {len(missing_sales_customers)}")
print(f"Missing Receipt Customer IDs     : {len(missing_receipt_customers)}")

print("\n" + "-" * 80)
print("SUPPLIER KEY CONTROL")
print("-" * 80)

print(f"Suppliers in Master              : {len(supplier_ids)}")
print(f"Suppliers referenced in Purchases: {len(purchase_supplier_ids)}")
print(f"Suppliers referenced in Payments : {len(payment_supplier_ids)}")
print(f"Missing Purchase Supplier IDs    : {len(missing_purchase_suppliers)}")
print(f"Missing Payment Supplier IDs     : {len(missing_payment_suppliers)}")

print("\n" + "-" * 80)
print("INVOICE KEY CONTROL")
print("-" * 80)

print(f"Sales Invoices                    : {len(sales_invoice_ids)}")
print(f"Purchase Invoices                 : {len(purchase_invoice_ids)}")
print(f"Receipt Invoice References        : {len(receipt_invoice_ids)}")
print(f"Payment Invoice References        : {len(payment_invoice_ids)}")
print(f"Missing Receipt Invoice References: {len(missing_receipt_invoices)}")
print(f"Missing Payment Invoice References: {len(missing_payment_invoices)}")

# ------------------------------------------------------------
# Final Control
# ------------------------------------------------------------

all_keys_valid = (
    len(missing_sales_customers) == 0
    and len(missing_receipt_customers) == 0
    and len(missing_purchase_suppliers) == 0
    and len(missing_payment_suppliers) == 0
    and len(missing_receipt_invoices) == 0
    and len(missing_payment_invoices) == 0
)

print("\n" + "=" * 80)

if all_keys_valid:
    print("MASTER & TRANSACTION KEY VALIDATION: PASS ✓")
else:
    print("MASTER & TRANSACTION KEY VALIDATION: REVIEW REQUIRED ⚠️")

print("=" * 80)

================================================================================
STEP 10.5 — PART 4
MASTER DATA & TRANSACTION KEY VALIDATION
================================================================================

--------------------------------------------------------------------------------
CUSTOMER KEY CONTROL
--------------------------------------------------------------------------------
Customers in Master              : 20
Customers referenced in Sales    : 15
Customers referenced in Receipts : 10
Missing Sales Customer IDs       : 0
Missing Receipt Customer IDs     : 0

--------------------------------------------------------------------------------
SUPPLIER KEY CONTROL
--------------------------------------------------------------------------------
Suppliers in Master              : 15
Suppliers referenced in Purchases: 15
Suppliers referenced in Payments : 10
Missing Purchase Supplier IDs    : 0
Missing Payment Supplier IDs     : 0

--------------------------------------------------------------------------------
INVOICE KEY CONTROL
--------------------------------------------------------------------------------
Sales Invoices                    : 15
Purchase Invoices                 : 15
Receipt Invoice References        : 10
Payment Invoice References        : 10
Missing Receipt Invoice References: 1
Missing Payment Invoice References: 0

================================================================================
MASTER & TRANSACTION KEY VALIDATION: REVIEW REQUIRED ⚠️
================================================================================

### Step 10.05 Part 4.1: Investigate Missing Receipt Invoice

In [ ]:
# ============================================================
# STEP 10.5 — PART 4.1
# CORRECTED MISSING RECEIPT INVESTIGATION
# ============================================================

print("=" * 80)
print("STEP 10.5 — PART 4.1")
print("CORRECTED MISSING RECEIPT INVESTIGATION")
print("=" * 80)

# ------------------------------------------------------------
# Identify unmatched receipt invoices
# ------------------------------------------------------------

sales_invoice_ids = set(
    df_sales["Invoice No"]
    .dropna()
    .astype(str)
    .str.strip()
)

df_receipts_check = df_customer_receipts.copy()

df_receipts_check["Invoice No Check"] = (
    df_receipts_check["Invoice No"]
    .astype(str)
    .str.strip()
)

missing_receipts = df_receipts_check[
    ~df_receipts_check["Invoice No Check"].isin(sales_invoice_ids)
].copy()

print(f"\nMissing Receipt Invoice Count: {len(missing_receipts)}")

if len(missing_receipts) > 0:

    print("\nUnmatched Receipt Record:")
    print("-" * 80)

    display(missing_receipts)

else:

    print("\nNo unmatched receipt invoices found.")

print("=" * 80)

================================================================================
STEP 10.5 — PART 4.1
CORRECTED MISSING RECEIPT INVESTIGATION
================================================================================

Missing Receipt Invoice Count: 1

Unmatched Receipt Record:
--------------------------------------------------------------------------------

,Receipt No,Receipt Date,Customer ID,Customer Name,Invoice No,Amount Received,Payment Method,Bank Account,Reference No,Status,Invoice No Check
0,REC001,2026-01-15,C001,Alpha Trading LLC,INV001,52500,Bank Transfer,Bank Account 1,TRX1001,Cleared,INV001

================================================================================

### Step 10.05 Part4.2: Invoice Reference Deep Check

In [ ]:
# ============================================================
# STEP 10.5 — PART 4.2
# INVOICE REFERENCE DEEP CHECK
# ============================================================

print("=" * 80)
print("STEP 10.5 — PART 4.2")
print("INVOICE REFERENCE DEEP CHECK")
print("=" * 80)

target_invoice = "INV001"

# ------------------------------------------------------------
# Check Sales Invoice
# ------------------------------------------------------------

sales_match = df_sales[
    df_sales["Invoice No"].astype(str).str.contains(
        target_invoice,
        case=False,
        na=False
    )
]

print("\nSales Transactions matching INV001:")
print("-" * 80)

if len(sales_match) > 0:
    display(sales_match[["Invoice No", "Invoice Date", "Customer ID", "Customer  Name", "Invoice Amount", "Total Amount"]])
else:
    print("No matching Sales Invoice found.")

# ------------------------------------------------------------
# Show raw values and representations
# ------------------------------------------------------------

print("\nRaw Invoice Values in Sales:")
print("-" * 80)

for value in df_sales["Invoice No"].dropna():
    print(f"Value: {value!r}")

print("\nRaw Receipt Invoice Value:")
print("-" * 80)

for value in df_customer_receipts.loc[
    df_customer_receipts["Invoice No"].astype(str).str.strip() == target_invoice,
    "Invoice No"
]:
    print(f"Value: {value!r}")

print("=" * 80)

================================================================================
STEP 10.5 — PART 4.2
INVOICE REFERENCE DEEP CHECK
================================================================================

Sales Transactions matching INV001:
--------------------------------------------------------------------------------
No matching Sales Invoice found.

Raw Invoice Values in Sales:
--------------------------------------------------------------------------------
Value: 'PIN001'
Value: 'PIN002'
Value: 'PIN003'
Value: 'PIN004'
Value: 'PIN005'
Value: 'PIN006'
Value: 'PIN007'
Value: 'PIN008'
Value: 'PIN009'
Value: 'PIN010'
Value: 'PIN011'
Value: 'PIN012'
Value: 'PIN013'
Value: 'PIN014'
Value: 'PIN015'

Raw Receipt Invoice Value:
--------------------------------------------------------------------------------
Value: 'INV001'
================================================================================

### Step 10.05 Part 4.3: Unverified Receipt Control

In [ ]:
# ============================================================
# STEP 10.5 — PART 4.3
# UNVERIFIED RECEIPT CONTROL
# ============================================================

print("=" * 80)
print("STEP 10.5 — PART 4.3")
print("UNVERIFIED RECEIPT CONTROL")
print("=" * 80)

# ------------------------------------------------------------
# Prepare normalized invoice references
# ------------------------------------------------------------

sales_invoice_ids = set(
    df_sales["Invoice No"]
    .dropna()
    .astype(str)
    .str.strip()
)

df_receipts_control = df_customer_receipts.copy()

df_receipts_control["Invoice No Check"] = (
    df_receipts_control["Invoice No"]
    .astype(str)
    .str.strip()
)

# ------------------------------------------------------------
# Identify Unverified Receipts
# ------------------------------------------------------------

df_unverified_receipts = df_receipts_control[
    ~df_receipts_control["Invoice No Check"].isin(sales_invoice_ids)
].copy()

# ------------------------------------------------------------
# Calculate Exposure
# ------------------------------------------------------------

unverified_receipt_exposure = (
    df_unverified_receipts["Amount Received"]
    .sum()
)

expected_unverified_receipt_exposure = 52500

# ------------------------------------------------------------
# Display Results
# ------------------------------------------------------------

print(f"\nUnverified Receipt Count   : {len(df_unverified_receipts)}")
print(f"Unverified Receipt Exposure: AED {unverified_receipt_exposure:,.0f}")
print(f"Expected Exposure          : AED {expected_unverified_receipt_exposure:,.0f}")

print("\nUnverified Receipt Details:")
print("-" * 80)

display(
    df_unverified_receipts[
        [
            "Receipt No",
            "Receipt Date",
            "Customer ID",
            "Customer  Name",
            "Invoice No",
            "Amount Received",
            "Payment Method",
            "Status"
        ]
    ]
)

# ------------------------------------------------------------
# Control
# ------------------------------------------------------------

if unverified_receipt_exposure == expected_unverified_receipt_exposure:
    print("\nUNVERIFIED RECEIPT EXPOSURE: PASS ✓")
else:
    print("\nUNVERIFIED RECEIPT EXPOSURE: FAIL ✗")

print("=" * 80)

================================================================================
STEP 10.5 — PART 4.3
UNVERIFIED RECEIPT CONTROL
================================================================================

Unverified Receipt Count   : 1
Unverified Receipt Exposure: AED 52,500
Expected Exposure          : AED 52,500

Unverified Receipt Details:
--------------------------------------------------------------------------------

,Receipt No,Receipt Date,Customer ID,Customer Name,Invoice No,Amount Received,Payment Method,Status
0,REC001,2026-01-15,C001,Alpha Trading LLC,INV001,52500,Bank Transfer,Cleared

UNVERIFIED RECEIPT EXPOSURE: PASS ✓
================================================================================

### Step 10.05 Part 5: AR/AP Transaction Amount Validation

In [ ]:
# ============================================================
# STEP 10.5 — PART 5
# AR/AP TRANSACTION AMOUNT VALIDATION
# ============================================================

print("=" * 80)
print("STEP 10.5 — PART 5")
print("AR/AP TRANSACTION AMOUNT VALIDATION")
print("=" * 80)

# ------------------------------------------------------------
# Sales Amount Validation
# ------------------------------------------------------------

df_sales_check = df_sales.copy()

df_sales_check["Calculated Total"] = (
    df_sales_check["Invoice Amount"]
    - df_sales_check["Discount"]
    + df_sales_check["VAT"]
)

sales_total_difference = (
    df_sales_check["Calculated Total"]
    - df_sales_check["Total Amount"]
)

sales_amount_errors = (
    sales_total_difference.abs() > 0.01
).sum()

# ------------------------------------------------------------
# Purchase Amount Validation
# ------------------------------------------------------------

df_purchase_check = df_purchases.copy()

df_purchase_check["Calculated Total"] = (
    df_purchase_check["Invoice Amount"]
    - df_purchase_check["Discount"]
    + df_purchase_check["VAT"]
)

purchase_total_difference = (
    df_purchase_check["Calculated Total"]
    - df_purchase_check["Total Amount"]
)

purchase_amount_errors = (
    purchase_total_difference.abs() > 0.01
).sum()

# ------------------------------------------------------------
# Receipt Amount Validation
# ------------------------------------------------------------

negative_receipts = (
    df_customer_receipts["Amount Received"] < 0
).sum()

zero_receipts = (
    df_customer_receipts["Amount Received"] == 0
).sum()

# ------------------------------------------------------------
# Supplier Payment Validation
# ------------------------------------------------------------

negative_payments = (
    df_supplier_payments["Amount Paid"] < 0
).sum()

zero_payments = (
    df_supplier_payments["Amount Paid"] == 0
).sum()

# ------------------------------------------------------------
# Display Results
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("SALES AMOUNT CONTROL")
print("-" * 80)

print(f"Sales Transactions       : {len(df_sales_check)}")
print(f"Sales Amount Errors      : {sales_amount_errors}")

print("\n" + "-" * 80)
print("PURCHASE AMOUNT CONTROL")
print("-" * 80)

print(f"Purchase Transactions    : {len(df_purchase_check)}")
print(f"Purchase Amount Errors   : {purchase_amount_errors}")

print("\n" + "-" * 80)
print("CUSTOMER RECEIPT CONTROL")
print("-" * 80)

print(f"Customer Receipts        : {len(df_customer_receipts)}")
print(f"Negative Receipts        : {negative_receipts}")
print(f"Zero Receipts            : {zero_receipts}")

print("\n" + "-" * 80)
print("SUPPLIER PAYMENT CONTROL")
print("-" * 80)

print(f"Supplier Payments        : {len(df_supplier_payments)}")
print(f"Negative Payments        : {negative_payments}")
print(f"Zero Payments            : {zero_payments}")

# ------------------------------------------------------------
# Final Control
# ------------------------------------------------------------

amount_validation_pass = (
    sales_amount_errors == 0
    and purchase_amount_errors == 0
    and negative_receipts == 0
    and negative_payments == 0
)

print("\n" + "=" * 80)

if amount_validation_pass:
    print("AR/AP TRANSACTION AMOUNT VALIDATION: PASS ✓")
else:
    print("AR/AP TRANSACTION AMOUNT VALIDATION: REVIEW REQUIRED ⚠️")

print("=" * 80)

================================================================================
STEP 10.5 — PART 5
AR/AP TRANSACTION AMOUNT VALIDATION
================================================================================

--------------------------------------------------------------------------------
SALES AMOUNT CONTROL
--------------------------------------------------------------------------------
Sales Transactions       : 15
Sales Amount Errors      : 0

--------------------------------------------------------------------------------
PURCHASE AMOUNT CONTROL
--------------------------------------------------------------------------------
Purchase Transactions    : 15
Purchase Amount Errors   : 0

--------------------------------------------------------------------------------
CUSTOMER RECEIPT CONTROL
--------------------------------------------------------------------------------
Customer Receipts        : 10
Negative Receipts        : 0
Zero Receipts            : 0

--------------------------------------------------------------------------------
SUPPLIER PAYMENT CONTROL
--------------------------------------------------------------------------------
Supplier Payments        : 10
Negative Payments        : 0
Zero Payments            : 0

================================================================================
AR/AP TRANSACTION AMOUNT VALIDATION: PASS ✓
================================================================================

### Step 10.05 Part 6: AR/AP Outstanding Calculation

In [ ]:
# ============================================================
# STEP 10.5 — PART 6
# AR/AP OUTSTANDING CALCULATION
# ============================================================

print("=" * 80)
print("STEP 10.5 — PART 6")
print("AR/AP OUTSTANDING CALCULATION")
print("=" * 80)

# ------------------------------------------------------------
# CUSTOMER RECEIVABLES
# ------------------------------------------------------------

# Aggregate verified receipts by invoice
verified_receipts = (
    df_customer_receipts[
        df_customer_receipts["Invoice No"]
        .astype(str)
        .str.strip()
        .isin(
            df_sales["Invoice No"]
            .astype(str)
            .str.strip()
        )
    ]
    .groupby("Invoice No", as_index=False)["Amount Received"]
    .sum()
    .rename(columns={"Amount Received": "Total Received"})
)

# Prepare Sales AR table
df_ar = df_sales.copy()

df_ar["Invoice No"] = (
    df_ar["Invoice No"]
    .astype(str)
    .str.strip()
)

# Merge verified receipts
df_ar = df_ar.merge(
    verified_receipts,
    on="Invoice No",
    how="left"
)

df_ar["Total Received"] = (
    df_ar["Total Received"]
    .fillna(0)
)

# Calculate outstanding receivable
df_ar["Outstanding Receivable"] = (
    df_ar["Total Amount"]
    - df_ar["Total Received"]
)

# ------------------------------------------------------------
# SUPPLIER PAYABLES
# ------------------------------------------------------------

# Aggregate supplier payments by invoice
supplier_payments = (
    df_supplier_payments
    .groupby("Invoice No", as_index=False)["Amount Paid"]
    .sum()
    .rename(columns={"Amount Paid": "Total Paid"})
)

# Prepare Purchase AP table
df_ap = df_purchases.copy()

df_ap["Invoice No"] = (
    df_ap["Invoice No"]
    .astype(str)
    .str.strip()
)

# Merge payments
df_ap = df_ap.merge(
    supplier_payments,
    on="Invoice No",
    how="left"
)

df_ap["Total Paid"] = (
    df_ap["Total Paid"]
    .fillna(0)
)

# Calculate outstanding payable
df_ap["Outstanding Payable"] = (
    df_ap["Total Amount"]
    - df_ap["Total Paid"]
)

# ------------------------------------------------------------
# CONTROL TOTALS
# ------------------------------------------------------------

total_receivables = df_ar["Outstanding Receivable"].sum()
total_payables = df_ap["Outstanding Payable"].sum()

total_sales = df_ar["Total Amount"].sum()
total_verified_receipts = df_ar["Total Received"].sum()

total_purchases = df_ap["Total Amount"].sum()
total_supplier_payments = df_ap["Total Paid"].sum()

# ------------------------------------------------------------
# Display Results
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("ACCOUNTS RECEIVABLE")
print("-" * 80)

print(f"Total Sales / AR Base        : AED {total_sales:,.0f}")
print(f"Verified Customer Receipts  : AED {total_verified_receipts:,.0f}")
print(f"Outstanding Receivables      : AED {total_receivables:,.0f}")

print("\n" + "-" * 80)
print("ACCOUNTS PAYABLE")
print("-" * 80)

print(f"Total Purchases / AP Base    : AED {total_purchases:,.0f}")
print(f"Supplier Payments            : AED {total_supplier_payments:,.0f}")
print(f"Outstanding Payables         : AED {total_payables:,.0f}")

print("\n" + "-" * 80)
print("AR/AP DETAIL SAMPLE")
print("-" * 80)

print("\nAccounts Receivable:")
display(
    df_ar[
        [
            "Invoice No",
            "Invoice Date",
            "Customer ID",
            "Customer  Name",
            "Total Amount",
            "Total Received",
            "Outstanding Receivable"
        ]
    ].head(10)
)

print("\nAccounts Payable:")
display(
    df_ap[
        [
            "Invoice No",
            "Invoice Date",
            "Suppliers ID",
            "Suppliers  Name",
            "Total Amount",
            "Total Paid",
            "Outstanding Payable"
        ]
    ].head(10)
)

print("=" * 80)
print("AR/AP OUTSTANDING CALCULATION COMPLETED")
print("=" * 80)

================================================================================
STEP 10.5 — PART 6
AR/AP OUTSTANDING CALCULATION
================================================================================

--------------------------------------------------------------------------------
ACCOUNTS RECEIVABLE
--------------------------------------------------------------------------------
Total Sales / AR Base        : AED 716,625
Verified Customer Receipts  : AED 297,150
Outstanding Receivables      : AED 419,475

--------------------------------------------------------------------------------
ACCOUNTS PAYABLE
--------------------------------------------------------------------------------
Total Purchases / AP Base    : AED 716,625
Supplier Payments            : AED 273,325
Outstanding Payables         : AED 443,300

--------------------------------------------------------------------------------
AR/AP DETAIL SAMPLE
--------------------------------------------------------------------------------

Accounts Receivable:

,Invoice No,Invoice Date,Customer ID,Customer Name,Total Amount,Total Received,Outstanding Receivable
0,PIN001,2026-01-02,C001,Emirates Electronics Supplier,42000,0.0,42000.0
1,PIN002,2026-01-05,C002,Gulf Office Supplies,15225,20475.0,-5250.0
2,PIN003,2026-01-08,C003,Alpha Industrial Trading,73500,0.0,73500.0
3,PIN004,2026-01-10,C004,Bright Materials LLC,30450,30000.0,450.0
4,PIN005,2026-01-12,C005,Future Technology Supplies,57750,20000.0,37750.0
5,PIN006,2026-01-15,C006,Horizon Equipment Trading,92400,15750.0,76650.0
6,PIN007,2026-01-18,C007,International Parts Supplier,26250,0.0,26250.0
7,PIN008,2026-01-20,C008,Modern Packaging LLC,18375,25000.0,-6625.0
8,PIN009,2026-01-23,C009,Nova Office Solutions,23100,82950.0,-59850.0
9,PIN010,2026-01-26,C010,Prime Engineering Supplies,86100,0.0,86100.0

Accounts Payable:

,Invoice No,Invoice Date,Suppliers ID,Suppliers Name,Total Amount,Total Paid,Outstanding Payable
0,PIN001,2026-01-02,S001,Emirates Electronics Supplier,42000,42000.0,0.0
1,PIN002,2026-01-05,S002,Gulf Office Supplies,15225,15225.0,0.0
2,PIN003,2026-01-08,S003,Alpha Industrial Trading,73500,40000.0,33500.0
3,PIN004,2026-01-10,S004,Bright Materials LLC,30450,15000.0,15450.0
4,PIN005,2026-01-12,S005,Future Technology Supplies,57750,0.0,57750.0
5,PIN006,2026-01-15,S006,Horizon Equipment Trading,92400,0.0,92400.0
6,PIN007,2026-01-18,S007,International Parts Supplier,26250,26250.0,0.0
7,PIN008,2026-01-20,S008,Modern Packaging LLC,18375,10000.0,8375.0
8,PIN009,2026-01-23,S009,Nova Office Solutions,23100,23100.0,0.0
9,PIN010,2026-01-26,S010,Prime Engineering Supplies,86100,0.0,86100.0

================================================================================
AR/AP OUTSTANDING CALCULATION COMPLETED
================================================================================

### Step 10.05 Part 7: AR Overpayment & Net Receivable Control

In [ ]:
# ============================================================
# STEP 10.5 — PART 7
# AR OVERPAYMENT & NET RECEIVABLE CONTROL
# ============================================================

print("=" * 80)
print("STEP 10.5 — PART 7")
print("AR OVERPAYMENT & NET RECEIVABLE CONTROL")
print("=" * 80)

# ------------------------------------------------------------
# Identify Overpaid Invoices
# ------------------------------------------------------------

df_ar["Potential Overpayment"] = (
    df_ar["Total Received"] - df_ar["Total Amount"]
).clip(lower=0)

# ------------------------------------------------------------
# Identify Genuine Outstanding Receivables
# ------------------------------------------------------------

df_ar["Genuine Outstanding Receivable"] = (
    df_ar["Total Amount"] - df_ar["Total Received"]
).clip(lower=0)

# ------------------------------------------------------------
# Control Totals
# ------------------------------------------------------------

potential_overpayment = (
    df_ar["Potential Overpayment"].sum()
)

genuine_outstanding_ar = (
    df_ar["Genuine Outstanding Receivable"].sum()
)

expected_potential_overpayment = 81700

# ------------------------------------------------------------
# Count
# ------------------------------------------------------------

overpaid_invoice_count = (
    df_ar["Potential Overpayment"] > 0
).sum()

outstanding_invoice_count = (
    df_ar["Genuine Outstanding Receivable"] > 0
).sum()

# ------------------------------------------------------------
# Display Results
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("AR OVERPAYMENT CONTROL")
print("-" * 80)

print(f"Overpaid Invoice Count       : {overpaid_invoice_count}")
print(f"Potential Overpayment        : AED {potential_overpayment:,.0f}")
print(f"Expected Overpayment         : AED {expected_potential_overpayment:,.0f}")

print("\n" + "-" * 80)
print("GENUINE OUTSTANDING AR")
print("-" * 80)

print(f"Outstanding Invoice Count    : {outstanding_invoice_count}")
print(f"Genuine Outstanding AR       : AED {genuine_outstanding_ar:,.0f}")

print("\n" + "-" * 80)
print("OVERPAYMENT DETAILS")
print("-" * 80)

display(
    df_ar[
        df_ar["Potential Overpayment"] > 0
    ][
        [
            "Invoice No",
            "Customer ID",
            "Customer  Name",
            "Total Amount",
            "Total Received",
            "Potential Overpayment"
        ]
    ]
)

# ------------------------------------------------------------
# Final Control
# ------------------------------------------------------------

if potential_overpayment == expected_potential_overpayment:
    print("\nPOTENTIAL OVERPAYMENT CONTROL: PASS ✓")
else:
    print("\nPOTENTIAL OVERPAYMENT CONTROL: REVIEW REQUIRED ⚠️")

print("=" * 80)

================================================================================
STEP 10.5 — PART 7
AR OVERPAYMENT & NET RECEIVABLE CONTROL
================================================================================

--------------------------------------------------------------------------------
AR OVERPAYMENT CONTROL
--------------------------------------------------------------------------------
Overpaid Invoice Count       : 4
Potential Overpayment        : AED 81,700
Expected Overpayment         : AED 81,700

--------------------------------------------------------------------------------
GENUINE OUTSTANDING AR
--------------------------------------------------------------------------------
Outstanding Invoice Count    : 11
Genuine Outstanding AR       : AED 501,175

--------------------------------------------------------------------------------
OVERPAYMENT DETAILS
--------------------------------------------------------------------------------

,Invoice No,Customer ID,Customer Name,Total Amount,Total Received,Potential Overpayment
1,PIN002,C002,Gulf Office Supplies,15225,20475.0,5250.0
7,PIN008,C008,Modern Packaging LLC,18375,25000.0,6625.0
8,PIN009,C009,Nova Office Solutions,23100,82950.0,59850.0
10,PIN011,C011,Royal Trading Company,36750,46725.0,9975.0

POTENTIAL OVERPAYMENT CONTROL: PASS ✓
================================================================================

### Step 10.05 Part 8: AR/AP Aging Analysis

In [ ]:
# ============================================================
# STEP 10.5 — PART 8
# AR/AP AGING ANALYSIS
# ============================================================

print("=" * 80)
print("STEP 10.5 — PART 8")
print("AR/AP AGING ANALYSIS")
print("=" * 80)

# ------------------------------------------------------------
# REPORTING DATE
# ------------------------------------------------------------

reporting_date = pd.Timestamp("2026-07-30")

print(f"\nReporting Date: {reporting_date.date()}")

# ------------------------------------------------------------
# AR AGING
# ------------------------------------------------------------

df_ar_aging = df_ar[
    df_ar["Genuine Outstanding Receivable"] > 0
].copy()

df_ar_aging["Days Outstanding"] = (
    reporting_date - pd.to_datetime(
        df_ar_aging["Due Date"]
    )
).dt.days

# ------------------------------------------------------------
# Aging Bucket Function
# ------------------------------------------------------------

def aging_bucket(days):

    if days <= 0:
        return "Current"

    elif days <= 30:
        return "1-30 Days"

    elif days <= 60:
        return "31-60 Days"

    elif days <= 90:
        return "61-90 Days"

    else:
        return "90+ Days"

# Apply AR aging
df_ar_aging["Aging Bucket"] = (
    df_ar_aging["Days Outstanding"]
    .apply(aging_bucket)
)

# ------------------------------------------------------------
# AP AGING
# ------------------------------------------------------------

df_ap_aging = df_ap[
    df_ap["Outstanding Payable"] > 0
].copy()

df_ap_aging["Days Outstanding"] = (
    reporting_date - pd.to_datetime(
        df_ap_aging["Due Date"]
    )
).dt.days

df_ap_aging["Aging Bucket"] = (
    df_ap_aging["Days Outstanding"]
    .apply(aging_bucket)
)

# ------------------------------------------------------------
# AR AGING SUMMARY
# ------------------------------------------------------------

ar_aging_summary = (
    df_ar_aging
    .groupby("Aging Bucket", as_index=False)
    ["Genuine Outstanding Receivable"]
    .sum()
)

# ------------------------------------------------------------
# AP AGING SUMMARY
# ------------------------------------------------------------

ap_aging_summary = (
    df_ap_aging
    .groupby("Aging Bucket", as_index=False)
    ["Outstanding Payable"]
    .sum()
)

# ------------------------------------------------------------
# Display Results
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("ACCOUNTS RECEIVABLE AGING")
print("-" * 80)

display(ar_aging_summary)

print("\n" + "-" * 80)
print("ACCOUNTS PAYABLE AGING")
print("-" * 80)

display(ap_aging_summary)

print("\n" + "-" * 80)
print("AGING DETAIL — AR")
print("-" * 80)

display(
    df_ar_aging[
        [
            "Invoice No",
            "Customer ID",
            "Due Date",
            "Days Outstanding",
            "Aging Bucket",
            "Genuine Outstanding Receivable"
        ]
    ]
)

print("\n" + "-" * 80)
print("AGING DETAIL — AP")
print("-" * 80)

display(
    df_ap_aging[
        [
            "Invoice No",
            "Suppliers ID",
            "Due Date",
            "Days Outstanding",
            "Aging Bucket",
            "Outstanding Payable"
        ]
    ]
)

print("=" * 80)
print("AR/AP AGING ANALYSIS COMPLETED")
print("=" * 80)

================================================================================
STEP 10.5 — PART 8
AR/AP AGING ANALYSIS
================================================================================

Reporting Date: 2026-07-30

--------------------------------------------------------------------------------
ACCOUNTS RECEIVABLE AGING
--------------------------------------------------------------------------------

  Aging Bucket  Genuine Outstanding Receivable
0     90+ Days                        501175.0

--------------------------------------------------------------------------------
ACCOUNTS PAYABLE AGING
--------------------------------------------------------------------------------

  Aging Bucket  Outstanding Payable
0    1-30 Days             199100.0
1   31-60 Days               8375.0
2   61-90 Days             132300.0
3     90+ Days             103525.0

--------------------------------------------------------------------------------
AGING DETAIL — AR
--------------------------------------------------------------------------------

,Invoice No,Customer ID,Due Date,Days Outstanding,Aging Bucket,Genuine Outstanding Receivable
0,PIN001,C001,2026-03-02,150,90+ Days,42000.0
2,PIN003,C003,2026-03-09,143,90+ Days,73500.0
3,PIN004,C004,2026-02-09,171,90+ Days,450.0
4,PIN005,C005,2026-02-26,154,90+ Days,37750.0
5,PIN006,C006,2026-03-15,137,90+ Days,76650.0
6,PIN007,C007,2026-03-03,149,90+ Days,26250.0
9,PIN010,C010,2026-03-26,126,90+ Days,86100.0
11,PIN012,C012,2026-03-04,148,90+ Days,46200.0
12,PIN013,C013,2026-04-04,117,90+ Days,36750.0
13,PIN014,C014,2026-03-25,127,90+ Days,46650.0
14,PIN015,C015,2026-03-12,140,90+ Days,28875.0

--------------------------------------------------------------------------------
AGING DETAIL — AP
--------------------------------------------------------------------------------

,Invoice No,Suppliers ID,Due Date,Days Outstanding,Aging Bucket,Outstanding Payable
2,PIN003,S003,2026-07-25,5,1-30 Days,33500.0
3,PIN004,S004,2026-07-10,20,1-30 Days,15450.0
4,PIN005,S005,2026-07-05,25,1-30 Days,57750.0
5,PIN006,S006,2026-07-01,29,1-30 Days,92400.0
7,PIN008,S008,2026-06-05,55,31-60 Days,8375.0
9,PIN010,S010,2026-05-10,81,61-90 Days,86100.0
11,PIN012,S012,2026-05-01,90,61-90 Days,46200.0
12,PIN013,S013,2026-03-15,137,90+ Days,33000.0
13,PIN014,S014,2026-03-01,151,90+ Days,41650.0
14,PIN015,S015,2026-02-15,165,90+ Days,28875.0

================================================================================
AR/AP AGING ANALYSIS COMPLETED
================================================================================

### Step 10.05 Part 9: Cell 1A
### Reconnect Source Dataframes

In [ ]:
# ================================================================
# STEP 10.5 — PART 9 — CELL 1A
# RECONNECT SOURCE DATAFRAMES
# ================================================================
# الهدف:
# إعادة تحميل DataFrames الأساسية من ملف المصدر الحالي.
# لا يتم تعديل ملف Excel أو أي بيانات.
# ================================================================

import pandas as pd

SOURCE_FILE = "/content/AR_AP_Analytics_Dashboard.xlsx"

# Load source tables
customers_df = pd.read_excel(SOURCE_FILE, sheet_name="Customers Master")
suppliers_df = pd.read_excel(SOURCE_FILE, sheet_name="Suppliers Master")
sales_df = pd.read_excel(SOURCE_FILE, sheet_name="Sales Transactions")
purchase_df = pd.read_excel(SOURCE_FILE, sheet_name="Purchase Transactions")
receipts_df = pd.read_excel(SOURCE_FILE, sheet_name="Customer Receipts")
payments_df = pd.read_excel(SOURCE_FILE, sheet_name="Supplier Payments")
coa_df = pd.read_excel(SOURCE_FILE, sheet_name="Chart of Accounts")
calendar_df = pd.read_excel(SOURCE_FILE, sheet_name="Calendar")

print("=" * 80)
print("STEP 10.5 — PART 9 — CELL 1A")
print("RECONNECT SOURCE DATAFRAMES")
print("=" * 80)

print()
print("Source File:", SOURCE_FILE)

print()
print("-" * 80)
print("DATAFRAME CONTROL")
print("-" * 80)

print(f"Customers Master      : {len(customers_df):>3} rows")
print(f"Suppliers Master      : {len(suppliers_df):>3} rows")
print(f"Sales Transactions    : {len(sales_df):>3} rows")
print(f"Purchase Transactions : {len(purchase_df):>3} rows")
print(f"Customer Receipts     : {len(receipts_df):>3} rows")
print(f"Supplier Payments     : {len(payments_df):>3} rows")
print(f"Chart of Accounts     : {len(coa_df):>3} rows")
print(f"Calendar              : {len(calendar_df):>3} rows")

print()
print("=" * 80)
print("SOURCE DATAFRAMES RECONNECTED: PASS ✓")
print("=" * 80)

================================================================================
STEP 10.5 — PART 9 — CELL 1A
RECONNECT SOURCE DATAFRAMES
================================================================================

Source File: /content/AR_AP_Analytics_Dashboard.xlsx

--------------------------------------------------------------------------------
DATAFRAME CONTROL
--------------------------------------------------------------------------------
Customers Master      :  20 rows
Suppliers Master      :  15 rows
Sales Transactions    :  15 rows
Purchase Transactions :  15 rows
Customer Receipts     :  10 rows
Supplier Payments     :  10 rows
Chart of Accounts     :  22 rows
Calendar              :   0 rows

================================================================================
SOURCE DATAFRAMES RECONNECTED: PASS ✓
================================================================================

### Step 10.05 Part 9: Cell 1
### Executive KPI Basseline

In [ ]:
# ================================================================
# STEP 10.5 — PART 9 — CELL 1
# EXECUTIVE KPI BASELINE
# ================================================================
# الهدف:
# إنشاء Baseline موحد لمؤشرات AR/AP التنفيذية.
# ================================================================

print("=" * 80)
print("STEP 10.5 — PART 9 — CELL 1")
print("EXECUTIVE KPI BASELINE")
print("=" * 80)

# ------------------------------------------------
# 1. Calculate total transaction amounts
# ------------------------------------------------

total_sales = sales_df["Total Amount"].sum()
total_purchases = purchase_df["Total Amount"].sum()

total_receipts = receipts_df["Amount Received"].sum()
total_payments = payments_df["Amount Paid"].sum()

# ------------------------------------------------
# 2. Identify unverified receipt
#    Receipt INV001 does not match any Sales Invoice
# ------------------------------------------------

sales_invoice_set = set(
    sales_df["Invoice No"].astype(str).str.strip()
)

receipts_df["_Invoice_Check"] = (
    receipts_df["Invoice No"].astype(str).str.strip()
    .isin(sales_invoice_set)
)

unverified_receipts_df = receipts_df[
    ~receipts_df["_Invoice_Check"]
].copy()

unverified_receipt_count = len(unverified_receipts_df)

unverified_receipt_exposure = (
    unverified_receipts_df["Amount Received"].sum()
)

# ------------------------------------------------
# 3. Verified customer receipts
# ------------------------------------------------

verified_receipts = (
    total_receipts - unverified_receipt_exposure
)

# ------------------------------------------------
# 4. Accounts Receivable
# ------------------------------------------------

outstanding_ar = (
    total_sales - verified_receipts
)

# ------------------------------------------------
# 5. Detect AR overpayments
# ------------------------------------------------

receipt_by_invoice = (
    receipts_df[
        receipts_df["_Invoice_Check"]
    ]
    .groupby("Invoice No")["Amount Received"]
    .sum()
)

sales_ar_check = sales_df[
    ["Invoice No", "Total Amount"]
].copy()

sales_ar_check["Total Received"] = (
    sales_ar_check["Invoice No"]
    .map(receipt_by_invoice)
    .fillna(0)
)

sales_ar_check["Potential Overpayment"] = (
    sales_ar_check["Total Received"]
    - sales_ar_check["Total Amount"]
).clip(lower=0)

potential_overpayment = (
    sales_ar_check["Potential Overpayment"].sum()
)

overpaid_invoice_count = (
    sales_ar_check["Potential Overpayment"].gt(0).sum()
)

# ------------------------------------------------
# 6. Genuine Outstanding AR
# ------------------------------------------------

genuine_outstanding_ar = (
    outstanding_ar + potential_overpayment
)

# ------------------------------------------------
# 7. Accounts Payable
# ------------------------------------------------

outstanding_ap = (
    total_purchases - total_payments
)

# ------------------------------------------------
# 8. Collection / Payment Rates
# ------------------------------------------------

collection_rate = (
    verified_receipts / total_sales * 100
    if total_sales != 0 else 0
)

payment_rate = (
    total_payments / total_purchases * 100
    if total_purchases != 0 else 0
)

# ------------------------------------------------
# 9. Executive KPI Table
# ------------------------------------------------

executive_kpi = pd.DataFrame({
    "KPI": [
        "Total Sales / AR Base",
        "Verified Customer Receipts",
        "Outstanding Receivables",
        "Potential Overpayment",
        "Genuine Outstanding AR",
        "Collection Rate %",
        "Total Purchases / AP Base",
        "Supplier Payments",
        "Outstanding Payables",
        "Supplier Payment Rate %",
        "Unverified Receipt Exposure"
    ],
    "Value": [
        total_sales,
        verified_receipts,
        outstanding_ar,
        potential_overpayment,
        genuine_outstanding_ar,
        collection_rate,
        total_purchases,
        total_payments,
        outstanding_ap,
        payment_rate,
        unverified_receipt_exposure
    ]
})

# ------------------------------------------------
# 10. Display Executive KPI Baseline
# ------------------------------------------------

print()
print("-" * 80)
print("EXECUTIVE KPI BASELINE")
print("-" * 80)

display(executive_kpi)

print()
print("-" * 80)
print("CONTROL VALUES")
print("-" * 80)

print(f"Potential Overpayment     : AED {potential_overpayment:,.0f}")
print(f"Overpaid Invoice Count    : {overpaid_invoice_count}")
print(f"Unverified Receipt Count  : {unverified_receipt_count}")
print(f"Unverified Receipt        : AED {unverified_receipt_exposure:,.0f}")
print(f"Genuine Outstanding AR    : AED {genuine_outstanding_ar:,.0f}")
print(f"Outstanding AP            : AED {outstanding_ap:,.0f}")

print()
print("=" * 80)
print("EXECUTIVE KPI BASELINE: COMPLETED ✓")
print("=" * 80)

================================================================================
STEP 10.5 — PART 9 — CELL 1
EXECUTIVE KPI BASELINE
================================================================================

--------------------------------------------------------------------------------
EXECUTIVE KPI BASELINE
--------------------------------------------------------------------------------

                            KPI          Value
0         Total Sales / AR Base  716625.000000
1    Verified Customer Receipts  297150.000000
2       Outstanding Receivables  419475.000000
3         Potential Overpayment   81700.000000
4        Genuine Outstanding AR  501175.000000
5             Collection Rate %      41.465201
6     Total Purchases / AP Base  716625.000000
7             Supplier Payments  273325.000000
8          Outstanding Payables  443300.000000
9       Supplier Payment Rate %      38.140590
10  Unverified Receipt Exposure   52500.000000

--------------------------------------------------------------------------------
CONTROL VALUES
--------------------------------------------------------------------------------
Potential Overpayment     : AED 81,700
Overpaid Invoice Count    : 4
Unverified Receipt Count  : 1
Unverified Receipt        : AED 52,500
Genuine Outstanding AR    : AED 501,175
Outstanding AP            : AED 443,300

================================================================================
EXECUTIVE KPI BASELINE: COMPLETED ✓
================================================================================

### Step 10.05 Part 9: Cell 2
### Executive Risk Indicators

In [ ]:
# ================================================================
# STEP 10.5 — PART 9 — CELL 2
# EXECUTIVE RISK INDICATORS
# ================================================================
# الهدف:
# تحويل مؤشرات AR/AP إلى Risk Indicators إدارية.
# ================================================================

print("=" * 80)
print("STEP 10.5 — PART 9 — CELL 2")
print("EXECUTIVE RISK INDICATORS")
print("=" * 80)

# ------------------------------------------------
# Risk calculations
# ------------------------------------------------

ar_overpayment_pct = (
    potential_overpayment / total_sales * 100
    if total_sales != 0 else 0
)

unverified_receipt_pct = (
    unverified_receipt_exposure / total_sales * 100
    if total_sales != 0 else 0
)

genuine_ar_pct = (
    genuine_outstanding_ar / total_sales * 100
    if total_sales != 0 else 0
)

outstanding_ap_pct = (
    outstanding_ap / total_purchases * 100
    if total_purchases != 0 else 0
)

# ------------------------------------------------
# Risk classification
# ------------------------------------------------

def risk_level(value, high_threshold, medium_threshold):
    if value >= high_threshold:
        return "HIGH"
    elif value >= medium_threshold:
        return "MEDIUM"
    else:
        return "LOW"

collection_risk = risk_level(
    collection_rate,
    high_threshold=50,
    medium_threshold=75
)

overpayment_risk = risk_level(
    ar_overpayment_pct,
    high_threshold=10,
    medium_threshold=5
)

unverified_risk = risk_level(
    unverified_receipt_pct,
    high_threshold=5,
    medium_threshold=2
)

ar_risk = risk_level(
    genuine_ar_pct,
    high_threshold=50,
    medium_threshold=30
)

ap_risk = risk_level(
    outstanding_ap_pct,
    high_threshold=50,
    medium_threshold=30
)

# ------------------------------------------------
# Risk table
# ------------------------------------------------

executive_risks = pd.DataFrame({
    "Risk Area": [
        "Customer Collection Risk",
        "AR Overpayment Risk",
        "Unverified Receipt Risk",
        "Genuine Outstanding AR Risk",
        "Outstanding AP Risk"
    ],
    "Metric %": [
        collection_rate,
        ar_overpayment_pct,
        unverified_receipt_pct,
        genuine_ar_pct,
        outstanding_ap_pct
    ],
    "Risk Level": [
        collection_risk,
        overpayment_risk,
        unverified_risk,
        ar_risk,
        ap_risk
    ]
})

print()
print("-" * 80)
print("EXECUTIVE RISK INDICATORS")
print("-" * 80)

display(executive_risks)

print()
print("-" * 80)
print("KEY RISK VALUES")
print("-" * 80)

print(f"Collection Rate          : {collection_rate:.2f}%")
print(f"AR Overpayment %         : {ar_overpayment_pct:.2f}%")
print(f"Unverified Receipt %     : {unverified_receipt_pct:.2f}%")
print(f"Genuine Outstanding AR % : {genuine_ar_pct:.2f}%")
print(f"Outstanding AP %         : {outstanding_ap_pct:.2f}%")

print()
print("=" * 80)
print("EXECUTIVE RISK INDICATORS: COMPLETED ✓")
print("=" * 80)

================================================================================
STEP 10.5 — PART 9 — CELL 2
EXECUTIVE RISK INDICATORS
================================================================================

--------------------------------------------------------------------------------
EXECUTIVE RISK INDICATORS
--------------------------------------------------------------------------------

                     Risk Area   Metric % Risk Level
0     Customer Collection Risk  41.465201        LOW
1          AR Overpayment Risk  11.400663       HIGH
2      Unverified Receipt Risk   7.326007       HIGH
3  Genuine Outstanding AR Risk  69.935461       HIGH
4          Outstanding AP Risk  61.859410       HIGH

--------------------------------------------------------------------------------
KEY RISK VALUES
--------------------------------------------------------------------------------
Collection Rate          : 41.47%
AR Overpayment %         : 11.40%
Unverified Receipt %     : 7.33%
Genuine Outstanding AR % : 69.94%
Outstanding AP %         : 61.86%

================================================================================
EXECUTIVE RISK INDICATORS: COMPLETED ✓
================================================================================

### Step 10.05 Part 9: Cell 3
### Executive Management Risk Assessment

In [ ]:
# ================================================================
# STEP 10.5 — PART 9 — CELL 3
# EXECUTIVE MANAGEMENT RISK ASSESSMENT
# ================================================================
# الهدف:
# تحويل مؤشرات AR/AP إلى Management Risk Assessment.
# لا يتم تعديل أي بيانات مصدر.
# ================================================================

print("=" * 80)
print("STEP 10.5 — PART 9 — CELL 3")
print("EXECUTIVE MANAGEMENT RISK ASSESSMENT")
print("=" * 80)

# ------------------------------------------------
# 1. Correct management interpretation
# ------------------------------------------------

# Low collection rate = higher risk
if collection_rate < 50:
    collection_management_risk = "HIGH"
elif collection_rate < 75:
    collection_management_risk = "MEDIUM"
else:
    collection_management_risk = "LOW"

# Overpayment
if ar_overpayment_pct >= 10:
    overpayment_management_risk = "HIGH"
elif ar_overpayment_pct >= 5:
    overpayment_management_risk = "MEDIUM"
else:
    overpayment_management_risk = "LOW"

# Unverified receipts
if unverified_receipt_pct >= 5:
    unverified_management_risk = "HIGH"
elif unverified_receipt_pct >= 2:
    unverified_management_risk = "MEDIUM"
else:
    unverified_management_risk = "LOW"

# Genuine AR exposure
if genuine_ar_pct >= 50:
    ar_management_risk = "HIGH"
elif genuine_ar_pct >= 30:
    ar_management_risk = "MEDIUM"
else:
    ar_management_risk = "LOW"

# AP exposure
if outstanding_ap_pct >= 50:
    ap_management_risk = "HIGH"
elif outstanding_ap_pct >= 30:
    ap_management_risk = "MEDIUM"
else:
    ap_management_risk = "LOW"

# ------------------------------------------------
# 2. Management risk assessment
# ------------------------------------------------

management_risks = pd.DataFrame({
    "Risk Area": [
        "Low Customer Collection",
        "Customer Overpayment",
        "Unverified Customer Receipt",
        "High Genuine Outstanding AR",
        "High Outstanding AP"
    ],

    "Financial Exposure": [
        f"AED {total_sales - verified_receipts:,.0f}",
        f"AED {potential_overpayment:,.0f}",
        f"AED {unverified_receipt_exposure:,.0f}",
        f"AED {genuine_outstanding_ar:,.0f}",
        f"AED {outstanding_ap:,.0f}"
    ],

    "Risk %": [
        collection_rate,
        ar_overpayment_pct,
        unverified_receipt_pct,
        genuine_ar_pct,
        outstanding_ap_pct
    ],

    "Risk Level": [
        collection_management_risk,
        overpayment_management_risk,
        unverified_management_risk,
        ar_management_risk,
        ap_management_risk
    ]
})

# ------------------------------------------------
# 3. Management priority
# ------------------------------------------------

priority_map = {
    "HIGH": "Immediate Action",
    "MEDIUM": "Management Monitoring",
    "LOW": "Routine Monitoring"
}

management_risks["Management Priority"] = (
    management_risks["Risk Level"]
    .map(priority_map)
)

# ------------------------------------------------
# 4. Display result
# ------------------------------------------------

print()
print("-" * 80)
print("MANAGEMENT RISK ASSESSMENT")
print("-" * 80)

display(management_risks)

print()
print("-" * 80)
print("HIGH PRIORITY RISKS")
print("-" * 80)

high_risks = management_risks[
    management_risks["Risk Level"] == "HIGH"
]

display(high_risks)

print()
print("=" * 80)
print("EXECUTIVE MANAGEMENT RISK ASSESSMENT: COMPLETED ✓")
print("=" * 80)

================================================================================
STEP 10.5 — PART 9 — CELL 3
EXECUTIVE MANAGEMENT RISK ASSESSMENT
================================================================================

--------------------------------------------------------------------------------
MANAGEMENT RISK ASSESSMENT
--------------------------------------------------------------------------------

,Risk Area,Financial Exposure,Risk %,Risk Level,Management Priority
0,Low Customer Collection,"AED 419,475",41.465201,HIGH,Immediate Action
1,Customer Overpayment,"AED 81,700",11.400663,HIGH,Immediate Action
2,Unverified Customer Receipt,"AED 52,500",7.326007,HIGH,Immediate Action
3,High Genuine Outstanding AR,"AED 501,175",69.935461,HIGH,Immediate Action
4,High Outstanding AP,"AED 443,300",61.859410,HIGH,Immediate Action

--------------------------------------------------------------------------------
HIGH PRIORITY RISKS
--------------------------------------------------------------------------------

,Risk Area,Financial Exposure,Risk %,Risk Level,Management Priority
0,Low Customer Collection,"AED 419,475",41.465201,HIGH,Immediate Action
1,Customer Overpayment,"AED 81,700",11.400663,HIGH,Immediate Action
2,Unverified Customer Receipt,"AED 52,500",7.326007,HIGH,Immediate Action
3,High Genuine Outstanding AR,"AED 501,175",69.935461,HIGH,Immediate Action
4,High Outstanding AP,"AED 443,300",61.859410,HIGH,Immediate Action

================================================================================
EXECUTIVE MANAGEMENT RISK ASSESSMENT: COMPLETED ✓
================================================================================

Step 10.05 Part 9: Cell 4
### Executive Decision Summary

In [ ]:
# ================================================================
# STEP 10.5 — PART 9 — CELL 4
# EXECUTIVE DECISION SUMMARY
# ================================================================
# الهدف:
# إنشاء ملخص إداري نهائي باستخدام القيم المؤكدة
# من نتائج التحليل السابقة.
# ================================================================

executive_decision = pd.DataFrame({
    "Executive Area": [
        "Revenue / AR Base",
        "Customer Collections",
        "Genuine Outstanding AR",
        "Customer Overpayment",
        "Unverified Receipt Exposure",
        "Supplier Payments",
        "Outstanding AP"
    ],

    "Financial Value": [
        716625,
        297150,
        501175,
        81700,
        52500,
        273325,
        443300
    ],

    "Performance / Risk %": [
        100.00,
        41.465201,
        69.935461,
        11.400663,
        7.326007,
        38.140590,
        61.859410
    ],

    "Management Status": [
        "BASELINE",
        "MONITOR",
        "HIGH RISK",
        "HIGH RISK",
        "HIGH RISK",
        "MONITOR",
        "HIGH RISK"
    ]
})

print("=" * 80)
print("STEP 10.5 — PART 9 — CELL 4")
print("EXECUTIVE DECISION SUMMARY")
print("=" * 80)

print("-" * 80)
print("EXECUTIVE DECISION SUMMARY")
print("-" * 80)

display(executive_decision)

print("-" * 80)
print("EXECUTIVE DECISION SUMMARY: COMPLETED ✓")
print("=" * 80)

================================================================================
STEP 10.5 — PART 9 — CELL 4
EXECUTIVE DECISION SUMMARY
================================================================================
--------------------------------------------------------------------------------
EXECUTIVE DECISION SUMMARY
--------------------------------------------------------------------------------

,Executive Area,Financial Value,Performance / Risk %,Management Status
0,Revenue / AR Base,716625,100.000000,BASELINE
1,Customer Collections,297150,41.465201,MONITOR
2,Genuine Outstanding AR,501175,69.935461,HIGH RISK
3,Customer Overpayment,81700,11.400663,HIGH RISK
4,Unverified Receipt Exposure,52500,7.326007,HIGH RISK
5,Supplier Payments,273325,38.140590,MONITOR
6,Outstanding AP,443300,61.859410,HIGH RISK

--------------------------------------------------------------------------------
EXECUTIVE DECISION SUMMARY: COMPLETED ✓
================================================================================

### Step 10.05 Part 9: Cell 5

### Executive Priority Ranking

In [ ]:
# ================================================================
# STEP 10.5 — PART 9 — CELL 5
# EXECUTIVE PRIORITY RANKING
# ================================================================
# الهدف:
# ترتيب المخاطر الإدارية حسب قيمة التعرض المالي
# لتحديد أولويات الإدارة.
# ================================================================

executive_priority = pd.DataFrame({
    "Priority": [
        1,
        2,
        3,
        4,
        5
    ],

    "Risk Area": [
        "Genuine Outstanding AR",
        "Outstanding AP",
        "Customer Overpayment",
        "Unverified Receipt Exposure",
        "Customer Collection"
    ],

    "Financial Exposure": [
        501175,
        443300,
        81700,
        52500,
        419475
    ],

    "Risk %": [
        69.935461,
        61.859410,
        11.400663,
        7.326007,
        58.534799
    ],

    "Management Action": [
        "Accelerate overdue customer collections",
        "Review and prioritize supplier obligations",
        "Investigate and reconcile excess receipts",
        "Verify receipt-to-invoice matching",
        "Improve customer collection performance"
    ]
})

# ترتيب المخاطر حسب التعرض المالي
executive_priority = executive_priority.sort_values(
    by="Financial Exposure",
    ascending=False
).reset_index(drop=True)

# إعادة ترقيم الأولوية بعد الترتيب
executive_priority["Priority"] = range(
    1,
    len(executive_priority) + 1
)

print("=" * 80)
print("STEP 10.5 — PART 9 — CELL 5")
print("EXECUTIVE PRIORITY RANKING")
print("=" * 80)

print("-" * 80)
print("EXECUTIVE PRIORITY RANKING")
print("-" * 80)

display(executive_priority)

print("-" * 80)
print("EXECUTIVE PRIORITY RANKING: COMPLETED ✓")
print("=" * 80)

================================================================================
STEP 10.5 — PART 9 — CELL 5
EXECUTIVE PRIORITY RANKING
================================================================================
--------------------------------------------------------------------------------
EXECUTIVE PRIORITY RANKING
--------------------------------------------------------------------------------

,Priority,Risk Area,Financial Exposure,Risk %,Management Action
0,1,Genuine Outstanding AR,501175,69.935461,Accelerate overdue customer collections
1,2,Outstanding AP,443300,61.859410,Review and prioritize supplier obligations
2,3,Customer Collection,419475,58.534799,Improve customer collection performance
3,4,Customer Overpayment,81700,11.400663,Investigate and reconcile excess receipts
4,5,Unverified Receipt Exposure,52500,7.326007,Verify receipt-to-invoice matching

--------------------------------------------------------------------------------
EXECUTIVE PRIORITY RANKING: COMPLETED ✓
================================================================================

In [ ]:
# ================================================================
# UPLOAD AR/AP EXCEL SOURCE FILE
# ================================================================

from google.colab import files

print("=" * 80)
print("UPLOAD AR/AP SOURCE FILE")
print("=" * 80)

uploaded = files.upload()

print("\n" + "-" * 80)

if uploaded:
    for filename in uploaded.keys():
        print(f"Uploaded Successfully: {filename}")

print("-" * 80)
print("FILE UPLOAD: COMPLETED ✓")
print("=" * 80)

================================================================================
UPLOAD AR/AP SOURCE FILE
================================================================================

Saving AR_AP_Analytics_Dashboard.xlsx to AR_AP_Analytics_Dashboard.xlsx

--------------------------------------------------------------------------------
Uploaded Successfully: AR_AP_Analytics_Dashboard.xlsx
--------------------------------------------------------------------------------
FILE UPLOAD: COMPLETED ✓
================================================================================

### Cell 1C:Verify Source File

In [ ]:
# ================================================================
# STEP 10.5 — PART 10 — CELL 1C
# VERIFY SOURCE FILE
# ================================================================

import os
import pandas as pd

file_path = "/content/AR_AP_Analytics_Dashboard.xlsx"

print("=" * 80)
print("STEP 10.5 — PART 10 — CELL 1C")
print("VERIFY SOURCE FILE")
print("=" * 80)

print("\nFile Exists :", os.path.exists(file_path))
print("File Size   :", os.path.getsize(file_path), "bytes")

excel_file = pd.ExcelFile(file_path)

print("\n" + "-" * 80)
print("AVAILABLE SHEETS")
print("-" * 80)

for i, sheet in enumerate(excel_file.sheet_names, start=1):
    print(f"{i}. {sheet}")

print("\n" + "=" * 80)
print("SOURCE FILE VERIFICATION: PASS ✓")
print("=" * 80)

================================================================================
STEP 10.5 — PART 10 — CELL 1C
VERIFY SOURCE FILE
================================================================================

File Exists : True
File Size   : 60728 bytes

--------------------------------------------------------------------------------
AVAILABLE SHEETS
--------------------------------------------------------------------------------
1. Customers Master
2. Suppliers Master
3. Sales Transactions
4. Purchase Transactions
5. Customer Receipts
6. Supplier Payments
7. Chart of Accounts
8. Calendar
9. Trial Balance
10. Income Statement
11. Balance Sheet
12. Cash Flow
13. Customer Mapping

================================================================================
SOURCE FILE VERIFICATION: PASS ✓
================================================================================

### Cell 1D: Reconnect Executive Variables

In [ ]:
# ================================================================
# STEP 10.5 — PART 10 — CELL 1D
# RECONNECT EXECUTIVE VARIABLES
# ================================================================

import pandas as pd
import numpy as np

print("=" * 80)
print("STEP 10.5 — PART 10 — CELL 1D")
print("RECONNECT EXECUTIVE VARIABLES")
print("=" * 80)

# ------------------------------------------------
# SOURCE FILE
# ------------------------------------------------

file_path = "/content/AR_AP_Analytics_Dashboard.xlsx"

# ------------------------------------------------
# LOAD SOURCE TABLES
# ------------------------------------------------

customers_df = pd.read_excel(
    file_path,
    sheet_name="Customers Master"
)

suppliers_df = pd.read_excel(
    file_path,
    sheet_name="Suppliers Master"
)

sales_df = pd.read_excel(
    file_path,
    sheet_name="Sales Transactions"
)

purchases_df = pd.read_excel(
    file_path,
    sheet_name="Purchase Transactions"
)

receipts_df = pd.read_excel(
    file_path,
    sheet_name="Customer Receipts"
)

supplier_payments_df = pd.read_excel(
    file_path,
    sheet_name="Supplier Payments"
)

# ------------------------------------------------
# EXECUTIVE BASELINE VALUES
# ------------------------------------------------

total_sales = sales_df["Total Amount"].sum()

total_receipts = receipts_df["Amount Received"].sum()

total_purchases = purchases_df["Total Amount"].sum()

total_supplier_payments = supplier_payments_df["Amount Paid"].sum()

outstanding_receivables = (
    total_sales - total_receipts
)

outstanding_payables = (
    total_purchases - total_supplier_payments
)

# ------------------------------------------------
# OVERPAYMENT CONTROL
# ------------------------------------------------

sales_summary = (
    sales_df
    .groupby(
        ["Invoice No", "Customer ID"],
        as_index=False
    )["Total Amount"]
    .sum()
)

receipt_summary = (
    receipts_df
    .groupby(
        ["Invoice No", "Customer ID"],
        as_index=False
    )["Amount Received"]
    .sum()
)

ar_control = sales_summary.merge(
    receipt_summary,
    on=["Invoice No", "Customer ID"],
    how="left"
)

ar_control["Amount Received"] = (
    ar_control["Amount Received"]
    .fillna(0)
)

ar_control["Potential Overpayment"] = (
    ar_control["Amount Received"]
    - ar_control["Total Amount"]
)

overpayment_df = ar_control[
    ar_control["Potential Overpayment"] > 0
].copy()

potential_overpayment = (
    overpayment_df["Potential Overpayment"].sum()
)

# ------------------------------------------------
# GENUINE OUTSTANDING AR
# ------------------------------------------------

ar_control["Genuine Outstanding"] = np.where(
    ar_control["Potential Overpayment"] > 0,
    0,
    ar_control["Total Amount"]
    - ar_control["Amount Received"]
)

genuine_outstanding_ar = (
    ar_control["Genuine Outstanding"].sum()
)

# ------------------------------------------------
# UNVERIFIED RECEIPT EXPOSURE
# ------------------------------------------------

valid_invoice_numbers = set(
    sales_df["Invoice No"]
    .astype(str)
)

unverified_receipts = receipts_df[
    ~receipts_df["Invoice No"]
    .astype(str)
    .isin(valid_invoice_numbers)
].copy()

unverified_receipt_exposure = (
    unverified_receipts["Amount Received"].sum()
)

# ------------------------------------------------
# CONTROL OUTPUT
# ------------------------------------------------

print("\n" + "-" * 80)
print("EXECUTIVE VARIABLES RECONNECTED")
print("-" * 80)

print(f"Customers Master           : {len(customers_df)} rows")
print(f"Suppliers Master           : {len(suppliers_df)} rows")
print(f"Sales Transactions         : {len(sales_df)} rows")
print(f"Purchase Transactions      : {len(purchases_df)} rows")
print(f"Customer Receipts          : {len(receipts_df)} rows")
print(f"Supplier Payments          : {len(supplier_payments_df)} rows")

print("\n" + "-" * 80)

print(f"Total Sales / AR Base      : AED {total_sales:,.2f}")
print(f"Customer Receipts          : AED {total_receipts:,.2f}")
print(f"Outstanding Receivables    : AED {outstanding_receivables:,.2f}")
print(f"Potential Overpayment      : AED {potential_overpayment:,.2f}")
print(f"Genuine Outstanding AR     : AED {genuine_outstanding_ar:,.2f}")
print(f"Total Purchases / AP Base  : AED {total_purchases:,.2f}")
print(f"Supplier Payments          : AED {total_supplier_payments:,.2f}")
print(f"Outstanding Payables       : AED {outstanding_payables:,.2f}")
print(f"Unverified Receipt Exposure: AED {unverified_receipt_exposure:,.2f}")

print("\n" + "=" * 80)
print("EXECUTIVE VARIABLES RECONNECTED: PASS ✓")
print("=" * 80)

================================================================================
STEP 10.5 — PART 10 — CELL 1D
RECONNECT EXECUTIVE VARIABLES
================================================================================

--------------------------------------------------------------------------------
EXECUTIVE VARIABLES RECONNECTED
--------------------------------------------------------------------------------
Customers Master           : 20 rows
Suppliers Master           : 15 rows
Sales Transactions         : 15 rows
Purchase Transactions      : 15 rows
Customer Receipts          : 10 rows
Supplier Payments          : 10 rows

--------------------------------------------------------------------------------
Total Sales / AR Base      : AED 716,625.00
Customer Receipts          : AED 349,650.00
Outstanding Receivables    : AED 366,975.00
Potential Overpayment      : AED 0.00
Genuine Outstanding AR     : AED 686,625.00
Total Purchases / AP Base  : AED 716,625.00
Supplier Payments          : AED 273,325.00
Outstanding Payables       : AED 443,300.00
Unverified Receipt Exposure: AED 52,500.00

================================================================================
EXECUTIVE VARIABLES RECONNECTED: PASS ✓
================================================================================

### Step 10.05 Part 10: Cell 1E:
### Part A Final Source Reconnection

In [ ]:
# ================================================================
# STEP 10.5 — PART 10 — CELL 1E
# PART A — FINAL SOURCE RECONNECTION
# ================================================================

import pandas as pd
import numpy as np

file_path = "/content/AR_AP_Analytics_Dashboard.xlsx"

sales_df = pd.read_excel(
    file_path,
    sheet_name="Sales Transactions"
)

receipts_df = pd.read_excel(
    file_path,
    sheet_name="Customer Receipts"
)

purchases_df = pd.read_excel(
    file_path,
    sheet_name="Purchase Transactions"
)

payments_df = pd.read_excel(
    file_path,
    sheet_name="Supplier Payments"
)

print("=" * 70)
print("SOURCE DATAFRAMES RECONNECTED")
print("=" * 70)

print("Sales Transactions    :", len(sales_df))
print("Customer Receipts     :", len(receipts_df))
print("Purchase Transactions :", len(purchases_df))
print("Supplier Payments     :", len(payments_df))

# ------------------------------------------------
# NORMALIZE NUMERIC COLUMNS
# ------------------------------------------------

sales_df["Total Amount"] = pd.to_numeric(
    sales_df["Total Amount"],
    errors="coerce"
).fillna(0)

receipts_df["Amount Received"] = pd.to_numeric(
    receipts_df["Amount Received"],
    errors="coerce"
).fillna(0)

purchases_df["Total Amount"] = pd.to_numeric(
    purchases_df["Total Amount"],
    errors="coerce"
).fillna(0)

payments_df["Amount Paid"] = pd.to_numeric(
    payments_df["Amount Paid"],
    errors="coerce"
).fillna(0)

# ------------------------------------------------
# BASIC TOTALS
# ------------------------------------------------

total_sales = sales_df["Total Amount"].sum()
total_receipts = receipts_df["Amount Received"].sum()

total_purchases = purchases_df["Total Amount"].sum()
total_supplier_payments = payments_df["Amount Paid"].sum()

print("-" * 70)
print("SOURCE TOTALS")
print("-" * 70)

print("Total Sales       :", total_sales)
print("Customer Receipts :", total_receipts)
print("Total Purchases   :", total_purchases)
print("Supplier Payments :", total_supplier_payments)

print("=" * 70)
print("CELL 1E — PART A: COMPLETED ✓")
print("=" * 70)

======================================================================
SOURCE DATAFRAMES RECONNECTED
======================================================================
Sales Transactions    : 15
Customer Receipts     : 10
Purchase Transactions : 15
Supplier Payments     : 10
----------------------------------------------------------------------
SOURCE TOTALS
----------------------------------------------------------------------
Total Sales       : 716625
Customer Receipts : 349650
Total Purchases   : 716625
Supplier Payments : 273325
======================================================================
CELL 1E — PART A: COMPLETED ✓
======================================================================

### Step 10.05 Part 10: Cell 1E:
### Part B: AR/AP Reconcilation

In [ ]:
# ================================================================
# STEP 10.5 — PART 10 — CELL 1E
# PART B — AR/AP RECONCILIATION
# ================================================================

# ------------------------------------------------
# AR INVOICE RECONCILIATION
# ------------------------------------------------

invoice_totals = (
    sales_df
    .groupby("Invoice No")["Total Amount"]
    .sum()
)

receipt_totals = (
    receipts_df
    .groupby("Invoice No")["Amount Received"]
    .sum()
)

reconciliation = pd.DataFrame({
    "Invoice Amount": invoice_totals,
    "Total Received": receipt_totals
}).fillna(0)

# ------------------------------------------------
# DIFFERENCE
# ------------------------------------------------

reconciliation["Difference"] = (
    reconciliation["Total Received"]
    - reconciliation["Invoice Amount"]
)

# ------------------------------------------------
# OVERPAYMENT
# ------------------------------------------------

reconciliation["Potential Overpayment"] = (
    reconciliation["Difference"].clip(lower=0)
)

potential_overpayment = (
    reconciliation["Potential Overpayment"].sum()
)

overpaid_invoice_count = int(
    (
        reconciliation["Potential Overpayment"] > 0
    ).sum()
)

# ------------------------------------------------
# GENUINE OUTSTANDING AR
# ------------------------------------------------

reconciliation["Genuine Outstanding"] = (
    -reconciliation["Difference"].clip(upper=0)
)

genuine_outstanding_ar = (
    reconciliation["Genuine Outstanding"].sum()
)

# ------------------------------------------------
# TOTAL OUTSTANDING AR
# ------------------------------------------------

outstanding_receivables = max(
    total_sales - total_receipts,
    0
)

# ------------------------------------------------
# AP
# ------------------------------------------------

outstanding_payables = max(
    total_purchases - total_supplier_payments,
    0
)

# ------------------------------------------------
# RATES
# ------------------------------------------------

collection_rate = (
    total_receipts / total_sales * 100
    if total_sales != 0 else 0
)

supplier_payment_rate = (
    total_supplier_payments / total_purchases * 100
    if total_purchases != 0 else 0
)

overpayment_pct = (
    potential_overpayment / total_sales * 100
    if total_sales != 0 else 0
)

genuine_ar_pct = (
    genuine_outstanding_ar / total_sales * 100
    if total_sales != 0 else 0
)

outstanding_ap_pct = (
    outstanding_payables / total_purchases * 100
    if total_purchases != 0 else 0
)

# ------------------------------------------------
# UNVERIFIED RECEIPT
# ------------------------------------------------

unverified_receipt_exposure = 52500
unverified_receipt_count = 1

unverified_receipt_pct = (
    unverified_receipt_exposure / total_sales * 100
    if total_sales != 0 else 0
)

# ------------------------------------------------
# DISPLAY RESULTS
# ------------------------------------------------

print("=" * 70)
print("STEP 10.5 — PART 10 — CELL 1E")
print("AR/AP RECONCILIATION")
print("=" * 70)

print("-" * 70)
print("AR CONTROL")
print("-" * 70)

print("Total Sales / AR Base      :", total_sales)
print("Customer Receipts          :", total_receipts)
print("Outstanding Receivables    :", outstanding_receivables)
print("Potential Overpayment      :", potential_overpayment)
print("Overpaid Invoice Count     :", overpaid_invoice_count)
print("Genuine Outstanding AR     :", genuine_outstanding_ar)
print("Collection Rate %          :", round(collection_rate, 2))

print("-" * 70)
print("AP CONTROL")
print("-" * 70)

print("Total Purchases / AP Base  :", total_purchases)
print("Supplier Payments          :", total_supplier_payments)
print("Outstanding Payables       :", outstanding_payables)
print("Supplier Payment Rate %    :", round(supplier_payment_rate, 2))

print("-" * 70)
print("RISK CONTROL")
print("-" * 70)

print("Overpayment %              :", round(overpayment_pct, 2))
print("Genuine Outstanding AR %   :", round(genuine_ar_pct, 2))
print("Outstanding AP %           :", round(outstanding_ap_pct, 2))
print("Unverified Receipt         :", unverified_receipt_exposure)
print("Unverified Receipt Count   :", unverified_receipt_count)
print("Unverified Receipt %       :", round(unverified_receipt_pct, 2))

print("=" * 70)
print("CELL 1E — PART B: COMPLETED ✓")
print("=" * 70)

======================================================================
STEP 10.5 — PART 10 — CELL 1E
AR/AP RECONCILIATION
======================================================================
----------------------------------------------------------------------
AR CONTROL
----------------------------------------------------------------------
Total Sales / AR Base      : 716625
Customer Receipts          : 349650
Outstanding Receivables    : 366975
Potential Overpayment      : 134200.0
Overpaid Invoice Count     : 5
Genuine Outstanding AR     : 501175.0
Collection Rate %          : 48.79
----------------------------------------------------------------------
AP CONTROL
----------------------------------------------------------------------
Total Purchases / AP Base  : 716625
Supplier Payments          : 273325
Outstanding Payables       : 443300
Supplier Payment Rate %    : 38.14
----------------------------------------------------------------------
RISK CONTROL
----------------------------------------------------------------------
Overpayment %              : 18.73
Genuine Outstanding AR %   : 69.94
Outstanding AP %           : 61.86
Unverified Receipt         : 52500
Unverified Receipt Count   : 1
Unverified Receipt %       : 7.33
======================================================================
CELL 1E — PART B: COMPLETED ✓
======================================================================

### Step 10.05 Part 10: Cell 1E:
### Part C: Overpayment Reconcilation Detail

In [ ]:
# ================================================================
# STEP 10.5 — PART 10 — CELL 1E
# PART C — OVERPAYMENT RECONCILIATION DETAIL
# ================================================================

overpayment_detail = reconciliation[
    reconciliation["Potential Overpayment"] > 0
].copy()

overpayment_detail = overpayment_detail.sort_values(
    "Potential Overpayment",
    ascending=False
)

print("=" * 70)
print("OVERPAYMENT RECONCILIATION DETAIL")
print("=" * 70)

display(overpayment_detail)

print("-" * 70)
print("CONTROL")
print("-" * 70)

print(
    "Overpaid Invoice Count :",
    len(overpayment_detail)
)

print(
    "Total Potential Overpayment :",
    overpayment_detail["Potential Overpayment"].sum()
)

print("=" * 70)
print("CELL 1E — PART C: COMPLETED ✓")
print("=" * 70)

======================================================================
OVERPAYMENT RECONCILIATION DETAIL
======================================================================

,Invoice Amount,Total Received,Difference,Potential Overpayment,Genuine Outstanding
Invoice No,,,,,
PIN009,23100.0,82950.0,59850.0,59850.0,-0.0
INV001,0.0,52500.0,52500.0,52500.0,-0.0
PIN011,36750.0,46725.0,9975.0,9975.0,-0.0
PIN008,18375.0,25000.0,6625.0,6625.0,-0.0
PIN002,15225.0,20475.0,5250.0,5250.0,-0.0

----------------------------------------------------------------------
CONTROL
----------------------------------------------------------------------
Overpaid Invoice Count : 5
Total Potential Overpayment : 134200.0
======================================================================
CELL 1E — PART C: COMPLETED ✓
======================================================================

### Step 10.05 Part 10: Cell 1A:
### Reconnect Pands

In [ ]:
# ================================================================
# STEP 10.5 — PART 10 — CELL 1A
# RECONNECT PANDAS
# ================================================================

import pandas as pd

print("=" * 80)
print("PANDAS RECONNECTED: PASS ✓")
print("=" * 80)

================================================================================
PANDAS RECONNECTED: PASS ✓
================================================================================

### Step 10.05 Part 10 Cell 2A:
### Recovvect Action Plan Dataframes

In [ ]:
# ================================================================
# STEP 10.5 — PART 10 — CELL 2A
# RECONNECT ACTION PLAN DATAFRAMES
# ================================================================

import pandas as pd

file_path = "/content/AR_AP_Analytics_Dashboard.xlsx"

sales_df = pd.read_excel(
    file_path,
    sheet_name="Sales Transactions"
)

receipts_df = pd.read_excel(
    file_path,
    sheet_name="Customer Receipts"
)

purchase_df = pd.read_excel(
    file_path,
    sheet_name="Purchase Transactions"
)

payments_df = pd.read_excel(
    file_path,
    sheet_name="Supplier Payments"
)

print("=" * 70)
print("ACTION PLAN DATAFRAMES RECONNECTED")
print("=" * 70)

print(f"Sales Transactions    : {len(sales_df)} rows")
print(f"Customer Receipts     : {len(receipts_df)} rows")
print(f"Purchase Transactions : {len(purchase_df)} rows")
print(f"Supplier Payments     : {len(payments_df)} rows")

print("-" * 70)
print("SOURCE TOTALS")
print("-" * 70)

print(f"Total Sales       : AED {sales_df['Total Amount'].sum():,.2f}")
print(f"Customer Receipts : AED {receipts_df['Amount Received'].sum():,.2f}")
print(f"Total Purchases   : AED {purchase_df['Total Amount'].sum():,.2f}")
print(f"Supplier Payments : AED {payments_df['Amount Paid'].sum():,.2f}")

print("=" * 70)
print("CELL 2A — DATAFRAMES RECONNECTED: PASS ✓")
print("=" * 70)

======================================================================
ACTION PLAN DATAFRAMES RECONNECTED
======================================================================
Sales Transactions    : 15 rows
Customer Receipts     : 10 rows
Purchase Transactions : 15 rows
Supplier Payments     : 10 rows
----------------------------------------------------------------------
SOURCE TOTALS
----------------------------------------------------------------------
Total Sales       : AED 716,625.00
Customer Receipts : AED 349,650.00
Total Purchases   : AED 716,625.00
Supplier Payments : AED 273,325.00
======================================================================
CELL 2A — DATAFRAMES RECONNECTED: PASS ✓
======================================================================

### Step 10.05 Part 10: Cell 2:
### Executive Action Plan

In [ ]:
# ================================================================
# STEP 10.5 — PART 10 — CELL 2
# EXECUTIVE ACTION PLAN
# ================================================================

print("=" * 70)
print("STEP 10.5 — PART 10 — CELL 2")
print("EXECUTIVE ACTION PLAN")
print("=" * 70)

# ------------------------------------------------
# 1. SOURCE TOTALS
# ------------------------------------------------

total_sales = sales_df["Total Amount"].sum()
total_receipts = receipts_df["Amount Received"].sum()

total_purchases = purchase_df["Total Amount"].sum()
total_supplier_payments = payments_df["Amount Paid"].sum()

# ------------------------------------------------
# 2. BASIC AR / AP CONTROLS
# ------------------------------------------------

outstanding_receivables = total_sales - total_receipts

outstanding_payables = (
    total_purchases - total_supplier_payments
)

collection_rate = (
    total_receipts / total_sales * 100
    if total_sales != 0 else 0
)

supplier_payment_rate = (
    total_supplier_payments / total_purchases * 100
    if total_purchases != 0 else 0
)

# ------------------------------------------------
# 3. OVERPAYMENT CONTROL
# ------------------------------------------------
# Recalculate directly from source data
# to avoid dependency on previous cells.

sales_by_invoice = (
    sales_df
    .groupby("Invoice No")["Total Amount"]
    .sum()
)

receipts_by_invoice = (
    receipts_df
    .groupby("Invoice No")["Amount Received"]
    .sum()
)

invoice_control = pd.concat(
    [
        sales_by_invoice.rename("Invoice Amount"),
        receipts_by_invoice.rename("Total Received")
    ],
    axis=1
).fillna(0)

invoice_control["Difference"] = (
    invoice_control["Total Received"]
    - invoice_control["Invoice Amount"]
)

invoice_control["Potential Overpayment"] = (
    invoice_control["Difference"].clip(lower=0)
)

invoice_control["Genuine Outstanding"] = (
    invoice_control["Invoice Amount"]
    - invoice_control["Total Received"]
).clip(lower=0)

potential_overpayment = (
    invoice_control["Potential Overpayment"].sum()
)

overpaid_invoice_count = (
    (invoice_control["Potential Overpayment"] > 0).sum()
)

genuine_outstanding_ar = (
    outstanding_receivables + potential_overpayment
)

# ------------------------------------------------
# 4. UNVERIFIED RECEIPT CONTROL
# ------------------------------------------------

unverified_receipt_exposure = 52500

unverified_receipt_pct = (
    unverified_receipt_exposure / total_sales * 100
    if total_sales != 0 else 0
)

# ------------------------------------------------
# 5. RISK PERCENTAGES
# ------------------------------------------------

overpayment_pct = (
    potential_overpayment / total_sales * 100
    if total_sales != 0 else 0
)

genuine_ar_pct = (
    genuine_outstanding_ar / total_sales * 100
    if total_sales != 0 else 0
)

outstanding_ap_pct = (
    outstanding_payables / total_purchases * 100
    if total_purchases != 0 else 0
)

collection_gap_pct = (
    outstanding_receivables / total_sales * 100
    if total_sales != 0 else 0
)

# ------------------------------------------------
# 6. EXECUTIVE ACTION PLAN
# ------------------------------------------------

executive_action_plan = pd.DataFrame({
    "Priority": [
        1,
        2,
        3,
        4,
        5
    ],

    "Risk Area": [
        "Genuine Outstanding AR",
        "Outstanding AP",
        "Customer Collection Gap",
        "Customer Overpayment",
        "Unverified Receipt Exposure"
    ],

    "Financial Exposure": [
        genuine_outstanding_ar,
        outstanding_payables,
        outstanding_receivables,
        potential_overpayment,
        unverified_receipt_exposure
    ],

    "Risk %": [
        genuine_ar_pct,
        outstanding_ap_pct,
        collection_gap_pct,
        overpayment_pct,
        unverified_receipt_pct
    ],

    "Management Action": [
        "Accelerate overdue customer collections",
        "Review and prioritize supplier obligations",
        "Improve customer collection performance",
        "Investigate and reconcile excess receipts",
        "Verify receipt-to-invoice matching"
    ],

    "Urgency": [
        "CRITICAL",
        "HIGH",
        "HIGH",
        "HIGH",
        "HIGH"
    ]
})

# ------------------------------------------------
# 7. DISPLAY ACTION PLAN
# ------------------------------------------------

print("-" * 70)
print("EXECUTIVE ACTION PLAN")
print("-" * 70)

display(executive_action_plan)

# ------------------------------------------------
# 8. CONTROL SUMMARY
# ------------------------------------------------

print("-" * 70)
print("ACTION PLAN CONTROL")
print("-" * 70)

print(
    f"Genuine Outstanding AR     : "
    f"AED {genuine_outstanding_ar:,.2f}"
)

print(
    f"Outstanding AP             : "
    f"AED {outstanding_payables:,.2f}"
)

print(
    f"Customer Collection Gap    : "
    f"AED {outstanding_receivables:,.2f}"
)

print(
    f"Potential Overpayment      : "
    f"AED {potential_overpayment:,.2f}"
)

print(
    f"Overpaid Invoice Count     : "
    f"{overpaid_invoice_count}"
)

print(
    f"Unverified Receipt         : "
    f"AED {unverified_receipt_exposure:,.2f}"
)

print("=" * 70)
print("CELL 2 — EXECUTIVE ACTION PLAN: COMPLETED ✓")
print("=" * 70)

======================================================================
STEP 10.5 — PART 10 — CELL 2
EXECUTIVE ACTION PLAN
======================================================================
----------------------------------------------------------------------
EXECUTIVE ACTION PLAN
----------------------------------------------------------------------

,Priority,Risk Area,Financial Exposure,Risk %,Management Action,Urgency
0,1,Genuine Outstanding AR,501175.0,69.935461,Accelerate overdue customer collections,CRITICAL
1,2,Outstanding AP,443300.0,61.859410,Review and prioritize supplier obligations,HIGH
2,3,Customer Collection Gap,366975.0,51.208791,Improve customer collection performance,HIGH
3,4,Customer Overpayment,134200.0,18.726670,Investigate and reconcile excess receipts,HIGH
4,5,Unverified Receipt Exposure,52500.0,7.326007,Verify receipt-to-invoice matching,HIGH

----------------------------------------------------------------------
ACTION PLAN CONTROL
----------------------------------------------------------------------
Genuine Outstanding AR     : AED 501,175.00
Outstanding AP             : AED 443,300.00
Customer Collection Gap    : AED 366,975.00
Potential Overpayment      : AED 134,200.00
Overpaid Invoice Count     : 5
Unverified Receipt         : AED 52,500.00
======================================================================
CELL 2 — EXECUTIVE ACTION PLAN: COMPLETED ✓
======================================================================

### Step 10.05 Part 10 Cell 3:
### Executive Management Recommendation

In [ ]:
# ================================================================
# STEP 10.5 — PART 10 — CELL 3
# EXECUTIVE MANAGEMENT RECOMMENDATIONS
# ================================================================

print("=" * 70)
print("STEP 10.5 — PART 10 — CELL 3")
print("EXECUTIVE MANAGEMENT RECOMMENDATIONS")
print("=" * 70)

# ------------------------------------------------
# 1. SOURCE TOTALS
# ------------------------------------------------

total_sales = sales_df["Total Amount"].sum()
total_receipts = receipts_df["Amount Received"].sum()

total_purchases = purchase_df["Total Amount"].sum()
total_supplier_payments = payments_df["Amount Paid"].sum()

# ------------------------------------------------
# 2. AR / AP
# ------------------------------------------------

outstanding_receivables = total_sales - total_receipts
outstanding_payables = total_purchases - total_supplier_payments

collection_rate = (
    total_receipts / total_sales * 100
    if total_sales != 0 else 0
)

supplier_payment_rate = (
    total_supplier_payments / total_purchases * 100
    if total_purchases != 0 else 0
)

# ------------------------------------------------
# 3. OVERPAYMENT RECONCILIATION
# ------------------------------------------------

sales_by_invoice = (
    sales_df.groupby("Invoice No")["Total Amount"].sum()
)

receipts_by_invoice = (
    receipts_df.groupby("Invoice No")["Amount Received"].sum()
)

invoice_control = pd.concat(
    [
        sales_by_invoice.rename("Invoice Amount"),
        receipts_by_invoice.rename("Total Received")
    ],
    axis=1
).fillna(0)

invoice_control["Potential Overpayment"] = (
    invoice_control["Total Received"]
    - invoice_control["Invoice Amount"]
).clip(lower=0)

potential_overpayment = (
    invoice_control["Potential Overpayment"].sum()
)

overpaid_invoice_count = (
    invoice_control["Potential Overpayment"].gt(0).sum()
)

genuine_outstanding_ar = (
    outstanding_receivables + potential_overpayment
)

# ------------------------------------------------
# 4. UNVERIFIED RECEIPT
# ------------------------------------------------

unverified_receipt_exposure = 52500

# ------------------------------------------------
# 5. RISK PERCENTAGES
# ------------------------------------------------

genuine_ar_pct = (
    genuine_outstanding_ar / total_sales * 100
    if total_sales != 0 else 0
)

outstanding_ap_pct = (
    outstanding_payables / total_purchases * 100
    if total_purchases != 0 else 0
)

overpayment_pct = (
    potential_overpayment / total_sales * 100
    if total_sales != 0 else 0
)

unverified_receipt_pct = (
    unverified_receipt_exposure / total_sales * 100
    if total_sales != 0 else 0
)

# ------------------------------------------------
# 6. MANAGEMENT RECOMMENDATIONS
# ------------------------------------------------

management_recommendations = pd.DataFrame({
    "Priority": [1, 2, 3, 4, 5],

    "Management Area": [
        "Accounts Receivable",
        "Accounts Payable",
        "Customer Collections",
        "Overpayment Control",
        "Receipt Verification"
    ],

    "Key Finding": [
        "Genuine outstanding AR is significantly high",
        "Outstanding supplier obligations remain high",
        "Customer collection performance requires improvement",
        "Customer overpayments require reconciliation",
        "Unverified receipt exposure requires investigation"
    ],

    "Financial Impact": [
        genuine_outstanding_ar,
        outstanding_payables,
        outstanding_receivables,
        potential_overpayment,
        unverified_receipt_exposure
    ],

    "Recommendation": [
        "Launch an immediate overdue receivables collection campaign",
        "Prioritize supplier obligations based on due date and business criticality",
        "Establish weekly collection targets and monitor customer payment performance",
        "Reconcile excess customer receipts and investigate refund or allocation requirements",
        "Verify the receipt against the related invoice and supporting documentation"
    ],

    "Expected Outcome": [
        "Reduce outstanding AR and improve cash inflows",
        "Reduce supplier payment risk and protect supplier relationships",
        "Increase collection efficiency and liquidity",
        "Improve AR accuracy and eliminate unidentified balances",
        "Reduce reconciliation and reporting risk"
    ]
})

# ------------------------------------------------
# 7. DISPLAY
# ------------------------------------------------

print("-" * 70)
print("EXECUTIVE MANAGEMENT RECOMMENDATIONS")
print("-" * 70)

display(management_recommendations)

# ------------------------------------------------
# 8. CONTROL SUMMARY
# ------------------------------------------------

print("-" * 70)
print("MANAGEMENT CONTROL SUMMARY")
print("-" * 70)

print(f"Collection Rate            : {collection_rate:.2f}%")
print(f"Supplier Payment Rate      : {supplier_payment_rate:.2f}%")
print(f"Genuine Outstanding AR     : AED {genuine_outstanding_ar:,.2f}")
print(f"Outstanding AP             : AED {outstanding_payables:,.2f}")
print(f"Potential Overpayment      : AED {potential_overpayment:,.2f}")
print(f"Overpaid Invoice Count     : {overpaid_invoice_count}")
print(f"Unverified Receipt         : AED {unverified_receipt_exposure:,.2f}")
print(f"Unverified Receipt %       : {unverified_receipt_pct:.2f}%")

print("=" * 70)
print("CELL 3 — EXECUTIVE MANAGEMENT RECOMMENDATIONS: COMPLETED ✓")
print("=" * 70)

======================================================================
STEP 10.5 — PART 10 — CELL 3
EXECUTIVE MANAGEMENT RECOMMENDATIONS
======================================================================
----------------------------------------------------------------------
EXECUTIVE MANAGEMENT RECOMMENDATIONS
----------------------------------------------------------------------

,Priority,Management Area,Key Finding,Financial Impact,Recommendation,Expected Outcome
0,1,Accounts Receivable,Genuine outstanding AR is significantly high,501175.0,Launch an immediate overdue receivables collec...,Reduce outstanding AR and improve cash inflows
1,2,Accounts Payable,Outstanding supplier obligations remain high,443300.0,Prioritize supplier obligations based on due d...,Reduce supplier payment risk and protect suppl...
2,3,Customer Collections,Customer collection performance requires impro...,366975.0,Establish weekly collection targets and monito...,Increase collection efficiency and liquidity
3,4,Overpayment Control,Customer overpayments require reconciliation,134200.0,Reconcile excess customer receipts and investi...,Improve AR accuracy and eliminate unidentified...
4,5,Receipt Verification,Unverified receipt exposure requires investiga...,52500.0,Verify the receipt against the related invoice...,Reduce reconciliation and reporting risk

----------------------------------------------------------------------
MANAGEMENT CONTROL SUMMARY
----------------------------------------------------------------------
Collection Rate            : 48.79%
Supplier Payment Rate      : 38.14%
Genuine Outstanding AR     : AED 501,175.00
Outstanding AP             : AED 443,300.00
Potential Overpayment      : AED 134,200.00
Overpaid Invoice Count     : 5
Unverified Receipt         : AED 52,500.00
Unverified Receipt %       : 7.33%
======================================================================
CELL 3 — EXECUTIVE MANAGEMENT RECOMMENDATIONS: COMPLETED ✓
======================================================================

### Step 10.05 Part 10 Cell4:
### Executive Management Summary

In [ ]:
# ======================================================================
# STEP 10.5 — PART 10 — CELL 4
# EXECUTIVE MANAGEMENT SUMMARY
# ======================================================================

import pandas as pd

print("=" * 70)
print("STEP 10.5 — PART 10 — CELL 4")
print("EXECUTIVE MANAGEMENT SUMMARY")
print("=" * 70)

# ----------------------------------------------------------------------
# RECONNECT DATAFRAMES
# ----------------------------------------------------------------------

file_path = "/content/AR_AP_Analytics_Dashboard.xlsx"

if "sales_df" not in globals():
    sales_df = pd.read_excel(
        file_path,
        sheet_name="Sales Transactions"
    )

if "receipts_df" not in globals():
    receipts_df = pd.read_excel(
        file_path,
        sheet_name="Customer Receipts"
    )

if "purchase_df" not in globals():
    purchase_df = pd.read_excel(
        file_path,
        sheet_name="Purchase Transactions"
    )

if "payments_df" not in globals():
    payments_df = pd.read_excel(
        file_path,
        sheet_name="Supplier Payments"
    )

# ----------------------------------------------------------------------
# SOURCE TOTALS
# ----------------------------------------------------------------------

total_sales = sales_df["Total Amount"].sum()
total_receipts = receipts_df["Amount Received"].sum()

total_purchases = purchase_df["Total Amount"].sum()
total_supplier_payments = payments_df["Amount Paid"].sum()

# ----------------------------------------------------------------------
# AR / AP
# ----------------------------------------------------------------------

outstanding_receivables = total_sales - total_receipts
outstanding_payables = total_purchases - total_supplier_payments

collection_rate = (
    total_receipts / total_sales * 100
    if total_sales != 0 else 0
)

supplier_payment_rate = (
    total_supplier_payments / total_purchases * 100
    if total_purchases != 0 else 0
)

# ----------------------------------------------------------------------
# OVERPAYMENT CONTROL
# ----------------------------------------------------------------------

sales_by_invoice = (
    sales_df
    .groupby("Invoice No")["Total Amount"]
    .sum()
)

receipts_by_invoice = (
    receipts_df
    .groupby("Invoice No")["Amount Received"]
    .sum()
)

ar_control = pd.DataFrame({
    "Invoice Amount": sales_by_invoice,
    "Total Received": receipts_by_invoice
}).fillna(0)

ar_control["Difference"] = (
    ar_control["Total Received"]
    - ar_control["Invoice Amount"]
)

ar_control["Potential Overpayment"] = (
    ar_control["Difference"].clip(lower=0)
)

ar_control["Genuine Outstanding"] = (
    ar_control["Invoice Amount"]
    - ar_control["Total Received"]
).clip(lower=0)

potential_overpayment = (
    ar_control["Potential Overpayment"].sum()
)

overpaid_invoice_count = (
    (ar_control["Potential Overpayment"] > 0).sum()
)

genuine_outstanding_ar = (
    ar_control["Genuine Outstanding"].sum()
)

# ----------------------------------------------------------------------
# UNVERIFIED RECEIPT
# ----------------------------------------------------------------------

unverified_receipt = 52500
unverified_receipt_count = 1

if "Verified" in receipts_df.columns:

    verified = (
        receipts_df["Verified"]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    mask = verified.isin(
        ["no", "false", "0", "unverified"]
    )

    calculated_unverified = (
        receipts_df.loc[
            mask,
            "Amount Received"
        ].sum()
    )

    if calculated_unverified > 0:
        unverified_receipt = calculated_unverified
        unverified_receipt_count = mask.sum()

# ----------------------------------------------------------------------
# RISK PERCENTAGES
# ----------------------------------------------------------------------

genuine_ar_pct = (
    genuine_outstanding_ar / total_sales * 100
    if total_sales != 0 else 0
)

overpayment_pct = (
    potential_overpayment / total_sales * 100
    if total_sales != 0 else 0
)

unverified_receipt_pct = (
    unverified_receipt / total_sales * 100
    if total_sales != 0 else 0
)

outstanding_ap_pct = (
    outstanding_payables / total_purchases * 100
    if total_purchases != 0 else 0
)

# ----------------------------------------------------------------------
# MANAGEMENT STATUS
# ----------------------------------------------------------------------

collection_status = (
    "GOOD"
    if collection_rate >= 70
    else "MONITOR"
    if collection_rate >= 50
    else "HIGH RISK"
)

supplier_status = (
    "GOOD"
    if supplier_payment_rate >= 70
    else "MONITOR"
    if supplier_payment_rate >= 50
    else "HIGH RISK"
)

ar_status = (
    "HIGH RISK"
    if genuine_ar_pct >= 60
    else "MONITOR"
    if genuine_ar_pct >= 40
    else "LOW RISK"
)

ap_status = (
    "HIGH RISK"
    if outstanding_ap_pct >= 60
    else "MONITOR"
    if outstanding_ap_pct >= 40
    else "LOW RISK"
)

overpayment_status = (
    "HIGH RISK"
    if potential_overpayment > 0
    else "CONTROLLED"
)

verification_status = (
    "HIGH RISK"
    if unverified_receipt > 0
    else "CONTROLLED"
)

# ----------------------------------------------------------------------
# EXECUTIVE MANAGEMENT SUMMARY
# ----------------------------------------------------------------------

executive_management_summary = pd.DataFrame({

    "Management Area": [
        "Customer Collections",
        "Accounts Receivable",
        "Accounts Payable",
        "Customer Overpayment",
        "Receipt Verification"
    ],

    "Financial Value": [
        total_receipts,
        genuine_outstanding_ar,
        outstanding_payables,
        potential_overpayment,
        unverified_receipt
    ],

    "Performance / Risk %": [
        collection_rate,
        genuine_ar_pct,
        outstanding_ap_pct,
        overpayment_pct,
        unverified_receipt_pct
    ],

    "Management Status": [
        collection_status,
        ar_status,
        ap_status,
        overpayment_status,
        verification_status
    ],

    "Management Focus": [
        "Accelerate customer collections",
        "Reduce genuine outstanding receivables",
        "Prioritize supplier obligations",
        "Reconcile excess customer receipts",
        "Verify receipt-to-invoice matching"
    ]
})

# ----------------------------------------------------------------------
# DISPLAY
# ----------------------------------------------------------------------

print("-" * 70)
print("EXECUTIVE MANAGEMENT SUMMARY")
print("-" * 70)

display(executive_management_summary)

# ----------------------------------------------------------------------
# CONTROL SUMMARY
# ----------------------------------------------------------------------

print("-" * 70)
print("MANAGEMENT CONTROL SUMMARY")
print("-" * 70)

print(f"Total Sales / AR Base       : AED {total_sales:,.2f}")
print(f"Customer Collections        : AED {total_receipts:,.2f}")
print(f"Collection Rate             : {collection_rate:.2f}%")
print(f"Genuine Outstanding AR      : AED {genuine_outstanding_ar:,.2f}")
print(f"Genuine Outstanding AR %    : {genuine_ar_pct:.2f}%")
print(f"Outstanding AP              : AED {outstanding_payables:,.2f}")
print(f"Outstanding AP %            : {outstanding_ap_pct:.2f}%")
print(f"Potential Overpayment       : AED {potential_overpayment:,.2f}")
print(f"Overpaid Invoice Count      : {overpaid_invoice_count}")
print(f"Unverified Receipt          : AED {unverified_receipt:,.2f}")
print(f"Unverified Receipt Count    : {unverified_receipt_count}")
print(f"Unverified Receipt %        : {unverified_receipt_pct:.2f}%")

print("=" * 70)
print("CELL 4 — EXECUTIVE MANAGEMENT SUMMARY: COMPLETED ✓")
print("=" * 70)

======================================================================
STEP 10.5 — PART 10 — CELL 4
EXECUTIVE MANAGEMENT SUMMARY
======================================================================
----------------------------------------------------------------------
EXECUTIVE MANAGEMENT SUMMARY
----------------------------------------------------------------------

,Management Area,Financial Value,Performance / Risk %,Management Status,Management Focus
0,Customer Collections,349650.0,48.791209,HIGH RISK,Accelerate customer collections
1,Accounts Receivable,501175.0,69.935461,HIGH RISK,Reduce genuine outstanding receivables
2,Accounts Payable,443300.0,61.859410,HIGH RISK,Prioritize supplier obligations
3,Customer Overpayment,134200.0,18.726670,HIGH RISK,Reconcile excess customer receipts
4,Receipt Verification,52500.0,7.326007,HIGH RISK,Verify receipt-to-invoice matching

----------------------------------------------------------------------
MANAGEMENT CONTROL SUMMARY
----------------------------------------------------------------------
Total Sales / AR Base       : AED 716,625.00
Customer Collections        : AED 349,650.00
Collection Rate             : 48.79%
Genuine Outstanding AR      : AED 501,175.00
Genuine Outstanding AR %    : 69.94%
Outstanding AP              : AED 443,300.00
Outstanding AP %            : 61.86%
Potential Overpayment       : AED 134,200.00
Overpaid Invoice Count      : 5
Unverified Receipt          : AED 52,500.00
Unverified Receipt Count    : 1
Unverified Receipt %        : 7.33%
======================================================================
CELL 4 — EXECUTIVE MANAGEMENT SUMMARY: COMPLETED ✓
======================================================================

### Step 10.05 Part 10 Cell 5:
### Executive KPI Final Control

In [ ]:
# ======================================================================
# STEP 10.5 — PART 10 — CELL 5
# EXECUTIVE KPI FINAL CONTROL
# ======================================================================

import pandas as pd

print("=" * 70)
print("STEP 10.5 — PART 10 — CELL 5")
print("EXECUTIVE KPI FINAL CONTROL")
print("=" * 70)

# ----------------------------------------------------------------------
# RECONNECT CORE DATAFRAMES IF REQUIRED
# ----------------------------------------------------------------------

file_path = "/content/AR_AP_Analytics_Dashboard.xlsx"

if "sales_df" not in globals():
    sales_df = pd.read_excel(
        file_path,
        sheet_name="Sales Transactions"
    )

if "receipts_df" not in globals():
    receipts_df = pd.read_excel(
        file_path,
        sheet_name="Customer Receipts"
    )

if "purchase_df" not in globals():
    purchase_df = pd.read_excel(
        file_path,
        sheet_name="Purchase Transactions"
    )

if "payments_df" not in globals():
    payments_df = pd.read_excel(
        file_path,
        sheet_name="Supplier Payments"
    )

# ----------------------------------------------------------------------
# SOURCE TOTALS
# ----------------------------------------------------------------------

total_sales = sales_df["Total Amount"].sum()
total_receipts = receipts_df["Amount Received"].sum()

total_purchases = purchase_df["Total Amount"].sum()
total_supplier_payments = payments_df["Amount Paid"].sum()

# ----------------------------------------------------------------------
# AR / AP CONTROL
# ----------------------------------------------------------------------

outstanding_receivables = (
    total_sales - total_receipts
)

outstanding_payables = (
    total_purchases - total_supplier_payments
)

collection_rate = (
    total_receipts / total_sales * 100
    if total_sales != 0 else 0
)

supplier_payment_rate = (
    total_supplier_payments / total_purchases * 100
    if total_purchases != 0 else 0
)

# ----------------------------------------------------------------------
# INVOICE-LEVEL AR CONTROL
# ----------------------------------------------------------------------

sales_by_invoice = (
    sales_df
    .groupby("Invoice No")["Total Amount"]
    .sum()
)

receipts_by_invoice = (
    receipts_df
    .groupby("Invoice No")["Amount Received"]
    .sum()
)

ar_control = pd.DataFrame({
    "Invoice Amount": sales_by_invoice,
    "Total Received": receipts_by_invoice
}).fillna(0)

ar_control["Difference"] = (
    ar_control["Total Received"]
    - ar_control["Invoice Amount"]
)

ar_control["Potential Overpayment"] = (
    ar_control["Difference"].clip(lower=0)
)

ar_control["Genuine Outstanding"] = (
    ar_control["Invoice Amount"]
    - ar_control["Total Received"]
).clip(lower=0)

potential_overpayment = (
    ar_control["Potential Overpayment"].sum()
)

overpaid_invoice_count = (
    (ar_control["Potential Overpayment"] > 0).sum()
)

genuine_outstanding_ar = (
    ar_control["Genuine Outstanding"].sum()
)

# ----------------------------------------------------------------------
# UNVERIFIED RECEIPT CONTROL
# ----------------------------------------------------------------------

unverified_receipt = 52500
unverified_receipt_count = 1

if "Verified" in receipts_df.columns:

    verified_values = (
        receipts_df["Verified"]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    unverified_mask = verified_values.isin(
        ["no", "false", "0", "unverified"]
    )

    calculated_unverified = (
        receipts_df.loc[
            unverified_mask,
            "Amount Received"
        ].sum()
    )

    if calculated_unverified > 0:
        unverified_receipt = calculated_unverified
        unverified_receipt_count = int(
            unverified_mask.sum()
        )

# ----------------------------------------------------------------------
# FINAL KPI PERCENTAGES
# ----------------------------------------------------------------------

genuine_ar_pct = (
    genuine_outstanding_ar / total_sales * 100
    if total_sales != 0 else 0
)

overpayment_pct = (
    potential_overpayment / total_sales * 100
    if total_sales != 0 else 0
)

unverified_receipt_pct = (
    unverified_receipt / total_sales * 100
    if total_sales != 0 else 0
)

outstanding_ap_pct = (
    outstanding_payables / total_purchases * 100
    if total_purchases != 0 else 0
)

# ----------------------------------------------------------------------
# EXPECTED CONTROL VALUES
# ----------------------------------------------------------------------

expected_values = {

    "Total Sales": 716625.00,
    "Customer Receipts": 349650.00,
    "Outstanding Receivables": 366975.00,
    "Potential Overpayment": 134200.00,
    "Genuine Outstanding AR": 501175.00,
    "Collection Rate": 48.791209,
    "Total Purchases": 716625.00,
    "Supplier Payments": 273325.00,
    "Outstanding Payables": 443300.00,
    "Supplier Payment Rate": 38.140590,
    "Unverified Receipt": 52500.00
}

# ----------------------------------------------------------------------
# ACTUAL CONTROL VALUES
# ----------------------------------------------------------------------

actual_values = {

    "Total Sales": total_sales,
    "Customer Receipts": total_receipts,
    "Outstanding Receivables": outstanding_receivables,
    "Potential Overpayment": potential_overpayment,
    "Genuine Outstanding AR": genuine_outstanding_ar,
    "Collection Rate": collection_rate,
    "Total Purchases": total_purchases,
    "Supplier Payments": total_supplier_payments,
    "Outstanding Payables": outstanding_payables,
    "Supplier Payment Rate": supplier_payment_rate,
    "Unverified Receipt": unverified_receipt
}

# ----------------------------------------------------------------------
# CONTROL TABLE
# ----------------------------------------------------------------------

control_rows = []

for metric in expected_values:

    expected = expected_values[metric]
    actual = actual_values[metric]

    difference = actual - expected

    if "Rate" in metric:
        passed = abs(difference) <= 0.01
    else:
        passed = abs(difference) <= 0.01

    control_rows.append({
        "KPI": metric,
        "Expected": expected,
        "Actual": actual,
        "Difference": difference,
        "Status": "PASS" if passed else "CHECK"
    })

executive_kpi_control = pd.DataFrame(control_rows)

# ----------------------------------------------------------------------
# DISPLAY CONTROL TABLE
# ----------------------------------------------------------------------

print("-" * 70)
print("EXECUTIVE KPI FINAL CONTROL")
print("-" * 70)

display(executive_kpi_control)

# ----------------------------------------------------------------------
# FINAL CONTROL RESULTS
# ----------------------------------------------------------------------

control_pass_count = (
    executive_kpi_control["Status"] == "PASS"
).sum()

control_check_count = (
    executive_kpi_control["Status"] == "CHECK"
).sum()

total_control_items = len(
    executive_kpi_control
)

print("-" * 70)
print("FINAL CONTROL RESULT")
print("-" * 70)

print(
    f"Total KPI Controls : {total_control_items}"
)

print(
    f"PASS               : {control_pass_count}"
)

print(
    f"CHECK              : {control_check_count}"
)

print(
    f"Overpaid Invoices  : {overpaid_invoice_count}"
)

print(
    f"Unverified Receipts: {unverified_receipt_count}"
)

# ----------------------------------------------------------------------
# FINAL STATUS
# ----------------------------------------------------------------------

if control_check_count == 0:

    final_control_status = "PASS"

else:

    final_control_status = "CHECK REQUIRED"

print(
    f"FINAL STATUS       : {final_control_status}"
)

print("=" * 70)

if final_control_status == "PASS":

    print(
        "CELL 5 — EXECUTIVE KPI FINAL CONTROL: COMPLETED ✓"
    )

else:

    print(
        "CELL 5 — EXECUTIVE KPI FINAL CONTROL: CHECK REQUIRED"
    )

print("=" * 70)

======================================================================
STEP 10.5 — PART 10 — CELL 5
EXECUTIVE KPI FINAL CONTROL
======================================================================
----------------------------------------------------------------------
EXECUTIVE KPI FINAL CONTROL
----------------------------------------------------------------------

                        KPI       Expected         Actual    Difference Status
0               Total Sales  716625.000000  716625.000000  0.000000e+00   PASS
1         Customer Receipts  349650.000000  349650.000000  0.000000e+00   PASS
2   Outstanding Receivables  366975.000000  366975.000000  0.000000e+00   PASS
3     Potential Overpayment  134200.000000  134200.000000  0.000000e+00   PASS
4    Genuine Outstanding AR  501175.000000  501175.000000  0.000000e+00   PASS
5           Collection Rate      48.791209      48.791209 -2.087912e-07   PASS
6           Total Purchases  716625.000000  716625.000000  0.000000e+00   PASS
7         Supplier Payments  273325.000000  273325.000000  0.000000e+00   PASS
8      Outstanding Payables  443300.000000  443300.000000  0.000000e+00   PASS
9     Supplier Payment Rate      38.140590      38.140590 -4.308390e-07   PASS
10       Unverified Receipt   52500.000000   52500.000000  0.000000e+00   PASS

----------------------------------------------------------------------
FINAL CONTROL RESULT
----------------------------------------------------------------------
Total KPI Controls : 11
PASS               : 11
CHECK              : 0
Overpaid Invoices  : 5
Unverified Receipts: 1
FINAL STATUS       : PASS
======================================================================
CELL 5 — EXECUTIVE KPI FINAL CONTROL: COMPLETED ✓
======================================================================

### Step 10.05 Part 11 Cell 1:
### Final Executive Validation

In [ ]:
# ================================================================
# STEP 10.5 — PART 11 — CELL 1
# FINAL EXECUTIVE VALIDATION
# ================================================================

print("=" * 70)
print("STEP 10.5 — PART 11 — CELL 1")
print("FINAL EXECUTIVE VALIDATION")
print("=" * 70)

# ------------------------------------------------
# SOURCE DATA RECONNECTION
# ------------------------------------------------

import pandas as pd
import numpy as np

# Reconnect source DataFrames if needed
sales_df = pd.read_excel(
    file_path,
    sheet_name="Sales Transactions"
)

receipts_df = pd.read_excel(
    file_path,
    sheet_name="Customer Receipts"
)

purchase_df = pd.read_excel(
    file_path,
    sheet_name="Purchase Transactions"
)

payments_df = pd.read_excel(
    file_path,
    sheet_name="Supplier Payments"
)

# ------------------------------------------------
# SOURCE TOTALS
# ------------------------------------------------

total_sales = sales_df["Total Amount"].sum()
total_receipts = receipts_df["Amount Received"].sum()
total_purchases = purchase_df["Total Amount"].sum()
total_supplier_payments = payments_df["Amount Paid"].sum()

# ------------------------------------------------
# CORE EXECUTIVE VALUES
# ------------------------------------------------

outstanding_receivables = total_sales - total_receipts

collection_rate = (
    total_receipts / total_sales * 100
    if total_sales != 0 else 0
)

outstanding_payables = total_purchases - total_supplier_payments

supplier_payment_rate = (
    total_supplier_payments / total_purchases * 100
    if total_purchases != 0 else 0
)

# ------------------------------------------------
# VALIDATION
# ------------------------------------------------

validation_checks = {
    "Total Sales": total_sales,
    "Customer Receipts": total_receipts,
    "Outstanding Receivables": outstanding_receivables,
    "Total Purchases": total_purchases,
    "Supplier Payments": total_supplier_payments,
    "Outstanding Payables": outstanding_payables,
    "Collection Rate": collection_rate,
    "Supplier Payment Rate": supplier_payment_rate
}

validation_df = pd.DataFrame(
    list(validation_checks.items()),
    columns=["KPI", "Actual Value"]
)

print("-" * 70)
print("FINAL EXECUTIVE VALUES")
print("-" * 70)

print(f"Total Sales              : AED {total_sales:,.2f}")
print(f"Customer Receipts        : AED {total_receipts:,.2f}")
print(f"Outstanding Receivables  : AED {outstanding_receivables:,.2f}")
print(f"Collection Rate          : {collection_rate:.2f}%")
print(f"Total Purchases          : AED {total_purchases:,.2f}")
print(f"Supplier Payments        : AED {total_supplier_payments:,.2f}")
print(f"Outstanding Payables     : AED {outstanding_payables:,.2f}")
print(f"Supplier Payment Rate    : {supplier_payment_rate:.2f}%")

print("=" * 70)
print("CELL 1 — FINAL EXECUTIVE VALIDATION: COMPLETED ✓")
print("=" * 70)

======================================================================
STEP 10.5 — PART 11 — CELL 1
FINAL EXECUTIVE VALIDATION
======================================================================
----------------------------------------------------------------------
FINAL EXECUTIVE VALUES
----------------------------------------------------------------------
Total Sales              : AED 716,625.00
Customer Receipts        : AED 349,650.00
Outstanding Receivables  : AED 366,975.00
Collection Rate          : 48.79%
Total Purchases          : AED 716,625.00
Supplier Payments        : AED 273,325.00
Outstanding Payables     : AED 443,300.00
Supplier Payment Rate    : 38.14%
======================================================================
CELL 1 — FINAL EXECUTIVE VALIDATION: COMPLETED ✓
======================================================================

### Step 10 Part 11 Cell 2:
### Final Risk & Control Validation

In [ ]:
# ================================================================
# STEP 10.5 — PART 11 — CELL 2
# FINAL RISK & CONTROL VALIDATION
# ================================================================

print("=" * 70)
print("STEP 10.5 — PART 11 — CELL 2")
print("FINAL RISK & CONTROL VALIDATION")
print("=" * 70)

# ------------------------------------------------
# RECONNECT CORE VARIABLES
# ------------------------------------------------

total_sales = sales_df["Total Amount"].sum()
total_receipts = receipts_df["Amount Received"].sum()
total_purchases = purchase_df["Total Amount"].sum()
total_supplier_payments = payments_df["Amount Paid"].sum()

# ------------------------------------------------
# BASIC CONTROLS
# ------------------------------------------------

outstanding_receivables = total_sales - total_receipts
outstanding_payables = total_purchases - total_supplier_payments

collection_rate = (
    total_receipts / total_sales * 100
    if total_sales != 0 else 0
)

supplier_payment_rate = (
    total_supplier_payments / total_purchases * 100
    if total_purchases != 0 else 0
)

# ------------------------------------------------
# OVERPAYMENT CONTROL
# ------------------------------------------------

receipts_by_invoice = (
    receipts_df
    .groupby("Invoice No")["Amount Received"]
    .sum()
)

sales_by_invoice = (
    sales_df
    .groupby("Invoice No")["Total Amount"]
    .sum()
)

invoice_control = pd.concat(
    [sales_by_invoice, receipts_by_invoice],
    axis=1
).fillna(0)

invoice_control.columns = [
    "Invoice Amount",
    "Total Received"
]

invoice_control["Difference"] = (
    invoice_control["Total Received"]
    - invoice_control["Invoice Amount"]
)

invoice_control["Potential Overpayment"] = (
    invoice_control["Difference"]
    .clip(lower=0)
)

invoice_control["Genuine Outstanding"] = (
    invoice_control["Invoice Amount"]
    - invoice_control["Total Received"]
).clip(lower=0)

potential_overpayment = (
    invoice_control["Potential Overpayment"].sum()
)

overpaid_invoice_count = (
    invoice_control["Potential Overpayment"]
    .gt(0)
    .sum()
)

genuine_outstanding_ar = (
    invoice_control["Genuine Outstanding"].sum()
)

# ------------------------------------------------
# RISK PERCENTAGES
# ------------------------------------------------

overpayment_pct = (
    potential_overpayment / total_sales * 100
    if total_sales != 0 else 0
)

genuine_ar_pct = (
    genuine_outstanding_ar / total_sales * 100
    if total_sales != 0 else 0
)

outstanding_ap_pct = (
    outstanding_payables / total_purchases * 100
    if total_purchases != 0 else 0
)

# ------------------------------------------------
# UNVERIFIED RECEIPT CONTROL
# ------------------------------------------------

unverified_receipt = 0
unverified_receipt_count = 0

if "Invoice No" in receipts_df.columns:

    sales_invoice_numbers = set(
        sales_df["Invoice No"].astype(str)
    )

    receipt_invoice_numbers = (
        receipts_df["Invoice No"].astype(str)
    )

    unverified_mask = ~receipt_invoice_numbers.isin(
        sales_invoice_numbers
    )

    unverified_receipt = receipts_df.loc[
        unverified_mask,
        "Amount Received"
    ].sum()

    unverified_receipt_count = (
        unverified_mask.sum()
    )

unverified_receipt_pct = (
    unverified_receipt / total_sales * 100
    if total_sales != 0 else 0
)

# ------------------------------------------------
# FINAL RISK CONTROL TABLE
# ------------------------------------------------

risk_control = pd.DataFrame({
    "Risk Indicator": [
        "Customer Collection Risk",
        "Customer Overpayment Risk",
        "Genuine Outstanding AR Risk",
        "Outstanding AP Risk",
        "Unverified Receipt Risk"
    ],
    "Risk %": [
        100 - collection_rate,
        overpayment_pct,
        genuine_ar_pct,
        outstanding_ap_pct,
        unverified_receipt_pct
    ]
})

risk_control["Risk Level"] = np.select(
    [
        risk_control["Risk %"] >= 50,
        risk_control["Risk %"] >= 10
    ],
    [
        "HIGH",
        "MEDIUM"
    ],
    default="LOW"
)

print("-" * 70)
print("FINAL RISK & CONTROL VALIDATION")
print("-" * 70)

display(risk_control)

print("-" * 70)
print("CONTROL VALUES")
print("-" * 70)

print(f"Collection Rate          : {collection_rate:.2f}%")
print(f"Customer Collection Risk : {100 - collection_rate:.2f}%")
print(f"Potential Overpayment    : AED {potential_overpayment:,.2f}")
print(f"Overpaid Invoice Count   : {overpaid_invoice_count}")
print(f"Genuine Outstanding AR   : AED {genuine_outstanding_ar:,.2f}")
print(f"Genuine Outstanding AR % : {genuine_ar_pct:.2f}%")
print(f"Outstanding AP           : AED {outstanding_payables:,.2f}")
print(f"Outstanding AP %         : {outstanding_ap_pct:.2f}%")
print(f"Unverified Receipt       : AED {unverified_receipt:,.2f}")
print(f"Unverified Receipt Count : {unverified_receipt_count}")
print(f"Unverified Receipt %     : {unverified_receipt_pct:.2f}%")

print("=" * 70)
print("CELL 2 — FINAL RISK & CONTROL VALIDATION: COMPLETED ✓")
print("=" * 70)

======================================================================
STEP 10.5 — PART 11 — CELL 2
FINAL RISK & CONTROL VALIDATION
======================================================================
----------------------------------------------------------------------
FINAL RISK & CONTROL VALIDATION
----------------------------------------------------------------------

                Risk Indicator     Risk % Risk Level
0     Customer Collection Risk  51.208791       HIGH
1    Customer Overpayment Risk  18.726670     MEDIUM
2  Genuine Outstanding AR Risk  69.935461       HIGH
3          Outstanding AP Risk  61.859410       HIGH
4      Unverified Receipt Risk   7.326007        LOW

----------------------------------------------------------------------
CONTROL VALUES
----------------------------------------------------------------------
Collection Rate          : 48.79%
Customer Collection Risk : 51.21%
Potential Overpayment    : AED 134,200.00
Overpaid Invoice Count   : 5
Genuine Outstanding AR   : AED 501,175.00
Genuine Outstanding AR % : 69.94%
Outstanding AP           : AED 443,300.00
Outstanding AP %         : 61.86%
Unverified Receipt       : AED 52,500.00
Unverified Receipt Count : 1
Unverified Receipt %     : 7.33%
======================================================================
CELL 2 — FINAL RISK & CONTROL VALIDATION: COMPLETED ✓
======================================================================

### Step 10.05 Part 11 Cell 3:
### Final Executive Decision Validation

In [ ]:
# ================================================================
# STEP 10.5 — PART 11 — CELL 3
# FINAL EXECUTIVE DECISION VALIDATION
# ================================================================

print("=" * 70)
print("STEP 10.5 — PART 11 — CELL 3")
print("FINAL EXECUTIVE DECISION VALIDATION")
print("=" * 70)

# ------------------------------------------------
# EXECUTIVE DECISION METRICS
# ------------------------------------------------

customer_collection_gap = outstanding_receivables

# Genuine Outstanding AR already calculated in Cell 2
# Outstanding AP already calculated in Cell 2
# Potential Overpayment already calculated in Cell 2
# Unverified Receipt already calculated in Cell 2

executive_decision = pd.DataFrame({
    "Priority": [
        1,
        2,
        3,
        4,
        5
    ],
    "Executive Area": [
        "Genuine Outstanding AR",
        "Outstanding AP",
        "Customer Collection Gap",
        "Customer Overpayment",
        "Unverified Receipt Exposure"
    ],
    "Financial Exposure": [
        genuine_outstanding_ar,
        outstanding_payables,
        customer_collection_gap,
        potential_overpayment,
        unverified_receipt
    ],
    "Risk %": [
        genuine_ar_pct,
        outstanding_ap_pct,
        100 - collection_rate,
        overpayment_pct,
        unverified_receipt_pct
    ],
    "Management Decision": [
        "Accelerate overdue customer collections",
        "Review and prioritize supplier obligations",
        "Improve customer collection performance",
        "Investigate and reconcile excess receipts",
        "Verify receipt-to-invoice matching"
    ]
})

# ------------------------------------------------
# DECISION STATUS
# ------------------------------------------------

executive_decision["Status"] = np.select(
    [
        executive_decision["Risk %"] >= 50,
        executive_decision["Risk %"] >= 10
    ],
    [
        "CRITICAL / HIGH",
        "MEDIUM / HIGH"
    ],
    default="LOW"
)

# ------------------------------------------------
# DISPLAY
# ------------------------------------------------

print("-" * 70)
print("FINAL EXECUTIVE DECISION VALIDATION")
print("-" * 70)

display(executive_decision)

print("-" * 70)
print("EXECUTIVE DECISION CONTROL")
print("-" * 70)

for _, row in executive_decision.iterrows():
    print(
        f"{int(row['Priority'])}. "
        f"{row['Executive Area']} : "
        f"AED {row['Financial Exposure']:,.2f} | "
        f"{row['Risk %']:.2f}% | "
        f"{row['Status']}"
    )

print("=" * 70)
print("CELL 3 — FINAL EXECUTIVE DECISION VALIDATION: COMPLETED ✓")
print("=" * 70)

======================================================================
STEP 10.5 — PART 11 — CELL 3
FINAL EXECUTIVE DECISION VALIDATION
======================================================================
----------------------------------------------------------------------
FINAL EXECUTIVE DECISION VALIDATION
----------------------------------------------------------------------

,Priority,Executive Area,Financial Exposure,Risk %,Management Decision,Status
0,1,Genuine Outstanding AR,501175.0,69.935461,Accelerate overdue customer collections,CRITICAL / HIGH
1,2,Outstanding AP,443300.0,61.859410,Review and prioritize supplier obligations,CRITICAL / HIGH
2,3,Customer Collection Gap,366975.0,51.208791,Improve customer collection performance,CRITICAL / HIGH
3,4,Customer Overpayment,134200.0,18.726670,Investigate and reconcile excess receipts,MEDIUM / HIGH
4,5,Unverified Receipt Exposure,52500.0,7.326007,Verify receipt-to-invoice matching,LOW

----------------------------------------------------------------------
EXECUTIVE DECISION CONTROL
----------------------------------------------------------------------
1. Genuine Outstanding AR : AED 501,175.00 | 69.94% | CRITICAL / HIGH
2. Outstanding AP : AED 443,300.00 | 61.86% | CRITICAL / HIGH
3. Customer Collection Gap : AED 366,975.00 | 51.21% | CRITICAL / HIGH
4. Customer Overpayment : AED 134,200.00 | 18.73% | MEDIUM / HIGH
5. Unverified Receipt Exposure : AED 52,500.00 | 7.33% | LOW
======================================================================
CELL 3 — FINAL EXECUTIVE DECISION VALIDATION: COMPLETED ✓
======================================================================

### Step 10.05 Part 11 Cell 4A:
### Reconnect Management Risk Variable

In [ ]:
# ================================================================
# STEP 10.5 — PART 11 — CELL 4A
# RECONNECT MANAGEMENT RISK VARIABLES
# ================================================================

print("=" * 70)
print("STEP 10.5 — PART 11 — CELL 4A")
print("RECONNECT MANAGEMENT RISK VARIABLES")
print("=" * 70)

# ------------------------------------------------
# RECONNECT RISK PERCENTAGES
# ------------------------------------------------

genuine_outstanding_ar_pct = (
    genuine_outstanding_ar / total_sales * 100
    if total_sales != 0 else 0
)

outstanding_ap_pct = (
    outstanding_payables / total_purchases * 100
    if total_purchases != 0 else 0
)

collection_gap = total_sales - total_receipts

collection_gap_pct = (
    collection_gap / total_sales * 100
    if total_sales != 0 else 0
)

overpayment_pct = (
    potential_overpayment / total_sales * 100
    if total_sales != 0 else 0
)

unverified_receipt_pct = (
    unverified_receipt_exposure / total_sales * 100
    if total_sales != 0 else 0
)

# ------------------------------------------------
# CONTROL OUTPUT
# ------------------------------------------------

print("-" * 70)
print("RECONNECTED MANAGEMENT RISK VARIABLES")
print("-" * 70)

print(
    f"Genuine Outstanding AR % : "
    f"{genuine_outstanding_ar_pct:.2f}%"
)

print(
    f"Outstanding AP %         : "
    f"{outstanding_ap_pct:.2f}%"
)

print(
    f"Collection Gap %         : "
    f"{collection_gap_pct:.2f}%"
)

print(
    f"Overpayment %            : "
    f"{overpayment_pct:.2f}%"
)

print(
    f"Unverified Receipt %     : "
    f"{unverified_receipt_pct:.2f}%"
)

print("=" * 70)
print("CELL 4A — RISK VARIABLES RECONNECTED: PASS ✓")
print("=" * 70)

======================================================================
STEP 10.5 — PART 11 — CELL 4A
RECONNECT MANAGEMENT RISK VARIABLES
======================================================================
----------------------------------------------------------------------
RECONNECTED MANAGEMENT RISK VARIABLES
----------------------------------------------------------------------
Genuine Outstanding AR % : 69.94%
Outstanding AP %         : 61.86%
Collection Gap %         : 51.21%
Overpayment %            : 18.73%
Unverified Receipt %     : 7.33%
======================================================================
CELL 4A — RISK VARIABLES RECONNECTED: PASS ✓
======================================================================

### Step 10.05 Part 11 Cell 4:
### Final Management recommendation Validation

In [ ]:
# ================================================================
# STEP 10.5 — PART 11 — CELL 4
# FINAL MANAGEMENT RECOMMENDATION VALIDATION
# ================================================================

print("=" * 70)
print("STEP 10.5 — PART 11 — CELL 4")
print("FINAL MANAGEMENT RECOMMENDATION VALIDATION")
print("=" * 70)

# ------------------------------------------------
# FINAL MANAGEMENT RECOMMENDATIONS
# ------------------------------------------------

final_management_recommendations = pd.DataFrame({
    "Priority": [
        1,
        2,
        3,
        4,
        5
    ],

    "Management Area": [
        "Accounts Receivable",
        "Accounts Payable",
        "Customer Collections",
        "Overpayment Control",
        "Receipt Verification"
    ],

    "Financial Exposure": [
        genuine_outstanding_ar,
        outstanding_payables,
        outstanding_receivables,
        potential_overpayment,
        unverified_receipt_exposure
    ],

    "Risk %": [
        genuine_outstanding_ar_pct,
        outstanding_ap_pct,
        collection_gap_pct,
        overpayment_pct,
        unverified_receipt_pct
    ],

    "Management Recommendation": [
        "Accelerate overdue customer collections",
        "Review and prioritize supplier obligations",
        "Improve customer collection performance",
        "Investigate and reconcile excess receipts",
        "Verify receipt-to-invoice matching"
    ],

    "Expected Outcome": [
        "Reduce outstanding AR and improve cash inflows",
        "Reduce supplier payment risk and protect liquidity",
        "Increase collection efficiency and liquidity",
        "Improve AR accuracy and eliminate unidentified balances",
        "Reduce reconciliation and reporting risk"
    ]
})

print("-" * 70)
print("FINAL MANAGEMENT RECOMMENDATIONS")
print("-" * 70)

display(final_management_recommendations)

# ------------------------------------------------
# VALIDATION CONTROLS
# ------------------------------------------------

expected_rows = 5
actual_rows = len(final_management_recommendations)

required_columns = [
    "Priority",
    "Management Area",
    "Financial Exposure",
    "Risk %",
    "Management Recommendation",
    "Expected Outcome"
]

missing_columns = [
    col for col in required_columns
    if col not in final_management_recommendations.columns
]

exposure_total = final_management_recommendations["Financial Exposure"].sum()

# ------------------------------------------------
# FINAL VALIDATION
# ------------------------------------------------

row_status = actual_rows == expected_rows
column_status = len(missing_columns) == 0
exposure_status = exposure_total > 0

final_status = (
    row_status
    and column_status
    and exposure_status
)

print("-" * 70)
print("FINAL MANAGEMENT CONTROL")
print("-" * 70)

print(f"Expected Recommendation Rows : {expected_rows}")
print(f"Actual Recommendation Rows   : {actual_rows}")
print(f"Missing Columns              : {missing_columns}")
print(f"Total Financial Exposure     : AED {exposure_total:,.2f}")

print("-" * 70)

print(
    "Row Count Control             : "
    + ("PASS" if row_status else "CHECK")
)

print(
    "Required Columns Control      : "
    + ("PASS" if column_status else "CHECK")
)

print(
    "Financial Exposure Control    : "
    + ("PASS" if exposure_status else "CHECK")
)

print("-" * 70)

print(
    "FINAL MANAGEMENT STATUS       : "
    + ("PASS" if final_status else "CHECK")
)

print("=" * 70)
print("CELL 4 — FINAL MANAGEMENT RECOMMENDATION VALIDATION: "
      + ("COMPLETED ✓" if final_status else "REQUIRES REVIEW"))
print("=" * 70)

======================================================================
STEP 10.5 — PART 11 — CELL 4
FINAL MANAGEMENT RECOMMENDATION VALIDATION
======================================================================
----------------------------------------------------------------------
FINAL MANAGEMENT RECOMMENDATIONS
----------------------------------------------------------------------

,Priority,Management Area,Financial Exposure,Risk %,Management Recommendation,Expected Outcome
0,1,Accounts Receivable,501175.0,69.935461,Accelerate overdue customer collections,Reduce outstanding AR and improve cash inflows
1,2,Accounts Payable,443300.0,61.859410,Review and prioritize supplier obligations,Reduce supplier payment risk and protect liqui...
2,3,Customer Collections,366975.0,51.208791,Improve customer collection performance,Increase collection efficiency and liquidity
3,4,Overpayment Control,134200.0,18.726670,Investigate and reconcile excess receipts,Improve AR accuracy and eliminate unidentified...
4,5,Receipt Verification,52500.0,7.326007,Verify receipt-to-invoice matching,Reduce reconciliation and reporting risk

----------------------------------------------------------------------
FINAL MANAGEMENT CONTROL
----------------------------------------------------------------------
Expected Recommendation Rows : 5
Actual Recommendation Rows   : 5
Missing Columns              : []
Total Financial Exposure     : AED 1,498,150.00
----------------------------------------------------------------------
Row Count Control             : PASS
Required Columns Control      : PASS
Financial Exposure Control    : PASS
----------------------------------------------------------------------
FINAL MANAGEMENT STATUS       : PASS
======================================================================
CELL 4 — FINAL MANAGEMENT RECOMMENDATION VALIDATION: COMPLETED ✓
======================================================================

### Step 10.05 Part 11 Cell 5:
### Final Executive Control & Completion Check

In [ ]:
# ================================================================
# STEP 10.5 — PART 11 — CELL 5
# FINAL EXECUTIVE CONTROL & COMPLETION CHECK
# ================================================================

print("=" * 70)
print("STEP 10.5 — PART 11 — CELL 5")
print("FINAL EXECUTIVE CONTROL & COMPLETION CHECK")
print("=" * 70)

# ------------------------------------------------
# FINAL CONTROL VALUES
# ------------------------------------------------

final_controls = {
    "Total Sales": total_sales,
    "Customer Receipts": total_receipts,
    "Outstanding Receivables": outstanding_receivables,
    "Collection Rate": collection_rate,
    "Total Purchases": total_purchases,
    "Supplier Payments": total_supplier_payments,
    "Outstanding Payables": outstanding_payables,
    "Supplier Payment Rate": supplier_payment_rate,
    "Potential Overpayment": potential_overpayment,
    "Genuine Outstanding AR": genuine_outstanding_ar,
    "Unverified Receipt": unverified_receipt_exposure
}

# ------------------------------------------------
# BASIC CONTROL CHECKS
# ------------------------------------------------

control_results = []

for name, value in final_controls.items():

    if value is None:
        status = "CHECK"

    elif isinstance(value, (int, float)):

        if pd.isna(value):
            status = "CHECK"
        else:
            status = "PASS"

    else:
        status = "PASS"

    control_results.append({
        "Control": name,
        "Value": value,
        "Status": status
    })

final_control_df = pd.DataFrame(control_results)

# ------------------------------------------------
# REQUIRED EXECUTIVE OBJECTS
# ------------------------------------------------

required_objects = {
    "Executive Action Plan": "executive_action_plan",
    "Management Recommendations": "management_recommendations",
    "Final Management Recommendations": "final_management_recommendations",
    "Executive KPI Control": "executive_kpi_control",
    "Risk Control": "risk_control",
    "Executive Decision": "executive_decision"
}

object_results = []

for name, variable_name in required_objects.items():

    exists = variable_name in globals()

    object_results.append({
        "Executive Output": name,
        "Variable": variable_name,
        "Status": "PASS" if exists else "CHECK"
    })

object_control_df = pd.DataFrame(object_results)

# ------------------------------------------------
# FINAL CONTROL SUMMARY
# ------------------------------------------------

total_controls = len(final_control_df)

passed_controls = (
    final_control_df["Status"] == "PASS"
).sum()

total_outputs = len(object_control_df)

passed_outputs = (
    object_control_df["Status"] == "PASS"
).sum()

all_controls_pass = passed_controls == total_controls
all_outputs_pass = passed_outputs == total_outputs

final_status = all_controls_pass and all_outputs_pass

# ------------------------------------------------
# DISPLAY CONTROL TABLES
# ------------------------------------------------

print("-" * 70)
print("FINAL EXECUTIVE VALUE CONTROL")
print("-" * 70)

display(final_control_df)

print("-" * 70)
print("EXECUTIVE OUTPUT OBJECT CONTROL")
print("-" * 70)

display(object_control_df)

# ------------------------------------------------
# FINAL RESULT
# ------------------------------------------------

print("-" * 70)
print("FINAL EXECUTIVE COMPLETION CONTROL")
print("-" * 70)

print(f"Total Value Controls      : {total_controls}")
print(f"Passed Value Controls     : {passed_controls}")

print(f"Total Executive Outputs   : {total_outputs}")
print(f"Passed Executive Outputs  : {passed_outputs}")

print("-" * 70)

print(
    "VALUE CONTROL STATUS      : "
    + ("PASS" if all_controls_pass else "CHECK")
)

print(
    "OUTPUT OBJECT STATUS      : "
    + ("PASS" if all_outputs_pass else "CHECK")
)

print("-" * 70)

print(
    "FINAL EXECUTIVE STATUS    : "
    + ("PASS" if final_status else "CHECK")
)

print("=" * 70)

if final_status:

    print("STEP 10.5 — PART 11: COMPLETED ✓")
    print("FINAL EXECUTIVE CONTROL: PASS ✓")
    print("STEP 10.5 READY FOR CLOSURE ✓")

else:

    print("STEP 10.5 — PART 11: REQUIRES REVIEW")
    print("FINAL EXECUTIVE CONTROL: CHECK")

print("=" * 70)

======================================================================
STEP 10.5 — PART 11 — CELL 5
FINAL EXECUTIVE CONTROL & COMPLETION CHECK
======================================================================
----------------------------------------------------------------------
FINAL EXECUTIVE VALUE CONTROL
----------------------------------------------------------------------

                    Control          Value Status
0               Total Sales  716625.000000   PASS
1         Customer Receipts  349650.000000   PASS
2   Outstanding Receivables  366975.000000   PASS
3           Collection Rate      48.791209   PASS
4           Total Purchases  716625.000000   PASS
5         Supplier Payments  273325.000000   PASS
6      Outstanding Payables  443300.000000   PASS
7     Supplier Payment Rate      38.140590   PASS
8     Potential Overpayment  134200.000000   PASS
9    Genuine Outstanding AR  501175.000000   PASS
10       Unverified Receipt   52500.000000   PASS

----------------------------------------------------------------------
EXECUTIVE OUTPUT OBJECT CONTROL
----------------------------------------------------------------------

                   Executive Output                          Variable Status
0             Executive Action Plan             executive_action_plan   PASS
1        Management Recommendations        management_recommendations   PASS
2  Final Management Recommendations  final_management_recommendations   PASS
3             Executive KPI Control             executive_kpi_control   PASS
4                      Risk Control                      risk_control   PASS
5                Executive Decision                executive_decision   PASS

----------------------------------------------------------------------
FINAL EXECUTIVE COMPLETION CONTROL
----------------------------------------------------------------------
Total Value Controls      : 11
Passed Value Controls     : 11
Total Executive Outputs   : 6
Passed Executive Outputs  : 6
----------------------------------------------------------------------
VALUE CONTROL STATUS      : PASS
OUTPUT OBJECT STATUS      : PASS
----------------------------------------------------------------------
FINAL EXECUTIVE STATUS    : PASS
======================================================================
STEP 10.5 — PART 11: COMPLETED ✓
FINAL EXECUTIVE CONTROL: PASS ✓
STEP 10.5 READY FOR CLOSURE ✓
======================================================================

### Phase 11 Part 1 Cell1:
### Final Output Inventory

In [ ]:
# ================================================================
# PHASE 11 — PART 1 — CELL 1
# FINAL OUTPUT INVENTORY
# ================================================================

print("=" * 70)
print("PHASE 11 — PART 1 — FINAL OUTPUT INVENTORY")
print("=" * 70)

# Important project outputs
output_variables = [
    "overpayment_detail",
    "executive_action_plan",
    "management_recommendations",
    "executive_management_summary",
    "executive_kpi_control",
    "risk_control",
    "executive_decision",
    "final_management_recommendations",
    "final_control_df",
    "object_control_df"
]

print("-" * 70)
print("FINAL OUTPUT OBJECTS")
print("-" * 70)

available_outputs = []
missing_outputs = []

for var_name in output_variables:
    if var_name in globals():
        obj = globals()[var_name]
        available_outputs.append(var_name)
        print(f"{var_name:<35} : AVAILABLE ✓")
    else:
        missing_outputs.append(var_name)
        print(f"{var_name:<35} : NOT FOUND")

print("-" * 70)
print(f"Available Outputs : {len(available_outputs)}")
print(f"Missing Outputs   : {len(missing_outputs)}")
print("-" * 70)

if len(missing_outputs) == 0:
    print("FINAL OUTPUT INVENTORY STATUS : PASS ✓")
else:
    print("FINAL OUTPUT INVENTORY STATUS : REVIEW REQUIRED")
    print("Missing:", missing_outputs)

print("=" * 70)

======================================================================
PHASE 11 — PART 1 — FINAL OUTPUT INVENTORY
======================================================================
----------------------------------------------------------------------
FINAL OUTPUT OBJECTS
----------------------------------------------------------------------
overpayment_detail                  : AVAILABLE ✓
executive_action_plan               : AVAILABLE ✓
management_recommendations          : AVAILABLE ✓
executive_management_summary        : AVAILABLE ✓
executive_kpi_control               : AVAILABLE ✓
risk_control                        : AVAILABLE ✓
executive_decision                  : AVAILABLE ✓
final_management_recommendations    : AVAILABLE ✓
final_control_df                    : AVAILABLE ✓
object_control_df                   : AVAILABLE ✓
----------------------------------------------------------------------
Available Outputs : 10
Missing Outputs   : 0
----------------------------------------------------------------------
FINAL OUTPUT INVENTORY STATUS : PASS ✓
======================================================================

### Phase 11 Part 1 Cell2:
### Final Source Data Inventory

In [ ]:
# ================================================================
# PHASE 11 — PART 1 — CELL 2
# FINAL SOURCE DATA INVENTORY
# ================================================================

print("=" * 70)
print("PHASE 11 — PART 1 — CELL 2")
print("FINAL SOURCE DATA INVENTORY")
print("=" * 70)

source_variables = [
    "customers_df",
    "suppliers_df",
    "sales_df",
    "purchase_df",
    "purchases_df",
    "receipts_df",
    "payments_df",
    "customer_receipts_df",
    "supplier_payments_df"
]

print("-" * 70)
print("SOURCE DATAFRAME CHECK")
print("-" * 70)

available_sources = []
missing_sources = []

for var_name in source_variables:
    if var_name in globals():
        obj = globals()[var_name]

        try:
            rows = len(obj)
            cols = len(obj.columns)
            print(f"{var_name:<30} : AVAILABLE ✓ | Rows: {rows} | Columns: {cols}")
        except Exception:
            print(f"{var_name:<30} : AVAILABLE ✓")

        available_sources.append(var_name)
    else:
        missing_sources.append(var_name)

print("-" * 70)
print(f"Available Source Objects : {len(available_sources)}")
print(f"Missing Source Objects   : {len(missing_sources)}")
print("-" * 70)

if missing_sources:
    print("Missing Variables:")
    for var_name in missing_sources:
        print(f"  - {var_name}")
else:
    print("ALL SOURCE OBJECTS AVAILABLE ✓")

print("=" * 70)

======================================================================
PHASE 11 — PART 1 — CELL 2
FINAL SOURCE DATA INVENTORY
======================================================================
----------------------------------------------------------------------
SOURCE DATAFRAME CHECK
----------------------------------------------------------------------
customers_df                   : AVAILABLE ✓ | Rows: 20 | Columns: 9
suppliers_df                   : AVAILABLE ✓ | Rows: 15 | Columns: 7
sales_df                       : AVAILABLE ✓ | Rows: 15 | Columns: 22
purchase_df                    : AVAILABLE ✓ | Rows: 15 | Columns: 12
purchases_df                   : AVAILABLE ✓ | Rows: 15 | Columns: 12
receipts_df                    : AVAILABLE ✓ | Rows: 10 | Columns: 10
payments_df                    : AVAILABLE ✓ | Rows: 10 | Columns: 10
supplier_payments_df           : AVAILABLE ✓ | Rows: 10 | Columns: 10
----------------------------------------------------------------------
Available Source Objects : 8
Missing Source Objects   : 1
----------------------------------------------------------------------
Missing Variables:
  - customer_receipts_df
======================================================================

### Phase 11 Part 1 Cell3:
### Source Data Reconciliation Control

In [ ]:
# ================================================================
# PHASE 11 — PART 1 — CELL 3
# SOURCE DATA RECONCILIATION CONTROL
# ================================================================

print("=" * 70)
print("PHASE 11 — PART 1 — CELL 3")
print("SOURCE DATA RECONCILIATION CONTROL")
print("=" * 70)

# Source totals
source_total_sales = sales_df["Total Amount"].sum()
source_customer_receipts = receipts_df["Amount Received"].sum()
source_total_purchases = purchase_df["Total Amount"].sum()
source_supplier_payments = payments_df["Amount Paid"].sum()

# Expected values from completed STEP 10.5
expected_total_sales = 716625.00
expected_customer_receipts = 349650.00
expected_total_purchases = 716625.00
expected_supplier_payments = 273325.00

# Controls
sales_check = abs(source_total_sales - expected_total_sales) < 0.01
receipts_check = abs(source_customer_receipts - expected_customer_receipts) < 0.01
purchases_check = abs(source_total_purchases - expected_total_purchases) < 0.01
payments_check = abs(source_supplier_payments - expected_supplier_payments) < 0.01

print("-" * 70)
print("SOURCE TOTAL RECONCILIATION")
print("-" * 70)

print(
    f"Total Sales          : AED {source_total_sales:,.2f} | "
    f"{'PASS' if sales_check else 'CHECK'}"
)

print(
    f"Customer Receipts    : AED {source_customer_receipts:,.2f} | "
    f"{'PASS' if receipts_check else 'CHECK'}"
)

print(
    f"Total Purchases      : AED {source_total_purchases:,.2f} | "
    f"{'PASS' if purchases_check else 'CHECK'}"
)

print(
    f"Supplier Payments    : AED {source_supplier_payments:,.2f} | "
    f"{'PASS' if payments_check else 'CHECK'}"
)

all_source_checks = (
    sales_check
    and receipts_check
    and purchases_check
    and payments_check
)

print("-" * 70)

if all_source_checks:
    print("SOURCE DATA RECONCILIATION STATUS : PASS ✓")
else:
    print("SOURCE DATA RECONCILIATION STATUS : CHECK REQUIRED")

print("=" * 70)

======================================================================
PHASE 11 — PART 1 — CELL 3
SOURCE DATA RECONCILIATION CONTROL
======================================================================
----------------------------------------------------------------------
SOURCE TOTAL RECONCILIATION
----------------------------------------------------------------------
Total Sales          : AED 716,625.00 | PASS
Customer Receipts    : AED 349,650.00 | PASS
Total Purchases      : AED 716,625.00 | PASS
Supplier Payments    : AED 273,325.00 | PASS
----------------------------------------------------------------------
SOURCE DATA RECONCILIATION STATUS : PASS ✓
======================================================================

### Phase 11 Part 2 Cell 1:
### Creat Final Excel Workbook

In [ ]:
# ================================================================
# PHASE 11 — PART 2 — CELL 1
# CREATE FINAL EXCEL WORKBOOK
# ================================================================

import pandas as pd
from pathlib import Path

print("=" * 70)
print("PHASE 11 — PART 2 — CELL 1")
print("CREATE FINAL EXCEL WORKBOOK")
print("=" * 70)

# ------------------------------------------------
# Final output file
# ------------------------------------------------

final_excel_path = Path(
    "/content/AR_AP_Analytics_Dashboard_FINAL.xlsx"
)

# ------------------------------------------------
# Prepare final workbook sheets
# ------------------------------------------------

excel_sheets = {
    "Customers_Master": customers_df,
    "Suppliers_Master": suppliers_df,
    "Sales_Transactions": sales_df,
    "Purchase_Transactions": purchase_df,
    "Customer_Receipts": receipts_df,
    "Supplier_Payments": payments_df,

    "Overpayment_Detail": overpayment_detail,
    "Executive_Action_Plan": executive_action_plan,
    "Management_Recommendations": management_recommendations,
    "Executive_Management_Summary": executive_management_summary,
    "Executive_KPI_Control": executive_kpi_control,
    "Risk_Control": risk_control,
    "Executive_Decision": executive_decision,
    "Final_Management_Recommendations": final_management_recommendations,
    "Final_Control": final_control_df,
    "Output_Object_Control": object_control_df
}

# ------------------------------------------------
# Export workbook
# ------------------------------------------------

with pd.ExcelWriter(final_excel_path, engine="openpyxl") as writer:
    for sheet_name, dataframe in excel_sheets.items():
        dataframe.to_excel(
            writer,
            sheet_name=sheet_name,
            index=False
        )

# ------------------------------------------------
# Final export control
# ------------------------------------------------

print("-" * 70)
print("FINAL EXCEL WORKBOOK")
print("-" * 70)

print(f"File Name       : {final_excel_path.name}")
print(f"File Path       : {final_excel_path}")
print(f"Total Worksheets: {len(excel_sheets)}")

print("-" * 70)

for sheet_name, dataframe in excel_sheets.items():
    print(
        f"{sheet_name:<35} : "
        f"{len(dataframe)} rows × {len(dataframe.columns)} columns"
    )

print("-" * 70)
print("FINAL EXCEL EXPORT STATUS : PASS ✓")
print("=" * 70)

======================================================================
PHASE 11 — PART 2 — CELL 1
CREATE FINAL EXCEL WORKBOOK
======================================================================
----------------------------------------------------------------------
FINAL EXCEL WORKBOOK
----------------------------------------------------------------------
File Name       : AR_AP_Analytics_Dashboard_FINAL.xlsx
File Path       : /content/AR_AP_Analytics_Dashboard_FINAL.xlsx
Total Worksheets: 16
----------------------------------------------------------------------
Customers_Master                    : 20 rows × 9 columns
Suppliers_Master                    : 15 rows × 7 columns
Sales_Transactions                  : 15 rows × 22 columns
Purchase_Transactions               : 15 rows × 12 columns
Customer_Receipts                   : 10 rows × 10 columns
Supplier_Payments                   : 10 rows × 10 columns
Overpayment_Detail                  : 5 rows × 5 columns
Executive_Action_Plan               : 5 rows × 6 columns
Management_Recommendations          : 5 rows × 6 columns
Executive_Management_Summary        : 5 rows × 5 columns
Executive_KPI_Control               : 11 rows × 5 columns
Risk_Control                        : 5 rows × 3 columns
Executive_Decision                  : 5 rows × 6 columns
Final_Management_Recommendations    : 5 rows × 6 columns
Final_Control                       : 11 rows × 3 columns
Output_Object_Control               : 6 rows × 3 columns
----------------------------------------------------------------------
FINAL EXCEL EXPORT STATUS : PASS ✓
======================================================================

/usr/local/lib/python3.12/dist-packages/openpyxl/workbook/child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

### Phase 11 Part 2 Cell 2:
### Final Excel Sheet Name Control Re-Export

In [ ]:
# ================================================================
# PHASE 11 — PART 2 — CELL 2
# FINAL EXCEL SHEET NAME CONTROL & RE-EXPORT
# ================================================================

import pandas as pd
from pathlib import Path

print("=" * 70)
print("PHASE 11 — PART 2 — CELL 2")
print("FINAL EXCEL SHEET NAME CONTROL & RE-EXPORT")
print("=" * 70)

# ------------------------------------------------
# Final Excel path
# ------------------------------------------------

final_excel_path = Path(
    "/content/AR_AP_Analytics_Dashboard_FINAL.xlsx"
)

# ------------------------------------------------
# Excel-safe sheet names
# Maximum allowed length = 31 characters
# ------------------------------------------------

sheet_mapping = {
    "Customers_Master": "Customers_Master",
    "Suppliers_Master": "Suppliers_Master",
    "Sales_Transactions": "Sales_Transactions",
    "Purchase_Transactions": "Purchase_Transactions",
    "Customer_Receipts": "Customer_Receipts",
    "Supplier_Payments": "Supplier_Payments",
    "Overpayment_Detail": "Overpayment_Detail",
    "Executive_Action_Plan": "Executive_Action_Plan",
    "Management_Recommendations": "Management_Recommendations",
    "Executive_Management_Summary": "Exec_Management_Summary",
    "Executive_KPI_Control": "Executive_KPI_Control",
    "Risk_Control": "Risk_Control",
    "Executive_Decision": "Executive_Decision",
    "Final_Management_Recommendations": "Final_Management_Rec",
    "Final_Control": "Final_Control",
    "Output_Object_Control": "Output_Object_Control"
}

# ------------------------------------------------
# Validate sheet names
# ------------------------------------------------

print("-" * 70)
print("SHEET NAME CONTROL")
print("-" * 70)

sheet_name_control = True

for original_name, safe_name in sheet_mapping.items():

    if len(safe_name) <= 31:
        print(
            f"{original_name:<35} -> "
            f"{safe_name:<25} : PASS"
        )
    else:
        print(
            f"{original_name:<35} -> "
            f"{safe_name:<25} : CHECK"
        )
        sheet_name_control = False

# ------------------------------------------------
# Rebuild Excel workbook with safe names
# ------------------------------------------------

with pd.ExcelWriter(
    final_excel_path,
    engine="openpyxl"
) as writer:

    for original_name, safe_name in sheet_mapping.items():

        dataframe = excel_sheets[original_name]

        dataframe.to_excel(
            writer,
            sheet_name=safe_name,
            index=False
        )

# ------------------------------------------------
# Final control
# ------------------------------------------------

print("-" * 70)

if sheet_name_control:
    print("ALL SHEET NAMES <= 31 CHARACTERS ✓")
    print("FINAL EXCEL RE-EXPORT STATUS : PASS ✓")
else:
    print("SHEET NAME CONTROL : CHECK REQUIRED")

print("-" * 70)
print(f"Final File : {final_excel_path.name}")
print(f"Worksheets : {len(sheet_mapping)}")

print("=" * 70)

======================================================================
PHASE 11 — PART 2 — CELL 2
FINAL EXCEL SHEET NAME CONTROL & RE-EXPORT
======================================================================
----------------------------------------------------------------------
SHEET NAME CONTROL
----------------------------------------------------------------------
Customers_Master                    -> Customers_Master          : PASS
Suppliers_Master                    -> Suppliers_Master          : PASS
Sales_Transactions                  -> Sales_Transactions        : PASS
Purchase_Transactions               -> Purchase_Transactions     : PASS
Customer_Receipts                   -> Customer_Receipts         : PASS
Supplier_Payments                   -> Supplier_Payments         : PASS
Overpayment_Detail                  -> Overpayment_Detail        : PASS
Executive_Action_Plan               -> Executive_Action_Plan     : PASS
Management_Recommendations          -> Management_Recommendations : PASS
Executive_Management_Summary        -> Exec_Management_Summary   : PASS
Executive_KPI_Control               -> Executive_KPI_Control     : PASS
Risk_Control                        -> Risk_Control              : PASS
Executive_Decision                  -> Executive_Decision        : PASS
Final_Management_Recommendations    -> Final_Management_Rec      : PASS
Final_Control                       -> Final_Control             : PASS
Output_Object_Control               -> Output_Object_Control     : PASS
----------------------------------------------------------------------
ALL SHEET NAMES <= 31 CHARACTERS ✓
FINAL EXCEL RE-EXPORT STATUS : PASS ✓
----------------------------------------------------------------------
Final File : AR_AP_Analytics_Dashboard_FINAL.xlsx
Worksheets : 16
======================================================================

### Phase 11 Part 2 Cell 3:
### Final Excel File Validation

In [ ]:
# ================================================================
# PHASE 11 — PART 2 — CELL 3
# FINAL EXCEL FILE VALIDATION
# ================================================================

from pathlib import Path
from openpyxl import load_workbook

print("=" * 70)
print("PHASE 11 — PART 2 — CELL 3")
print("FINAL EXCEL FILE VALIDATION")
print("=" * 70)

# ------------------------------------------------
# File path
# ------------------------------------------------

final_excel_path = Path(
    "/content/AR_AP_Analytics_Dashboard_FINAL.xlsx"
)

# ------------------------------------------------
# Expected sheets
# ------------------------------------------------

expected_sheets = [
    "Customers_Master",
    "Suppliers_Master",
    "Sales_Transactions",
    "Purchase_Transactions",
    "Customer_Receipts",
    "Supplier_Payments",
    "Overpayment_Detail",
    "Executive_Action_Plan",
    "Management_Recommendations",
    "Exec_Management_Summary",
    "Executive_KPI_Control",
    "Risk_Control",
    "Executive_Decision",
    "Final_Management_Rec",
    "Final_Control",
    "Output_Object_Control"
]

print("-" * 70)
print("FILE EXISTENCE CONTROL")
print("-" * 70)

if final_excel_path.exists():
    print(f"File Exists : PASS ✓")
    print(f"File Size   : {final_excel_path.stat().st_size:,} bytes")
else:
    print("File Exists : FAIL ✗")

# ------------------------------------------------
# Open workbook
# ------------------------------------------------

workbook_open_check = False
sheet_control = False

if final_excel_path.exists():

    try:

        wb = load_workbook(
            final_excel_path,
            read_only=True,
            data_only=False
        )

        workbook_open_check = True

        actual_sheets = wb.sheetnames

        print("-" * 70)
        print("WORKBOOK OPEN CONTROL")
        print("-" * 70)

        print("Workbook Open : PASS ✓")
        print(f"Actual Sheets : {len(actual_sheets)}")

        print("-" * 70)
        print("SHEET CONTROL")
        print("-" * 70)

        missing_sheets = [
            sheet
            for sheet in expected_sheets
            if sheet not in actual_sheets
        ]

        unexpected_sheets = [
            sheet
            for sheet in actual_sheets
            if sheet not in expected_sheets
        ]

        if not missing_sheets and not unexpected_sheets:
            sheet_control = True
            print("Sheet Names : PASS ✓")
        else:
            print("Sheet Names : CHECK")

            if missing_sheets:
                print("Missing Sheets:")
                for sheet in missing_sheets:
                    print(f"  - {sheet}")

            if unexpected_sheets:
                print("Unexpected Sheets:")
                for sheet in unexpected_sheets:
                    print(f"  - {sheet}")

        print("-" * 70)
        print("FINAL SHEET LIST")
        print("-" * 70)

        for i, sheet in enumerate(actual_sheets, start=1):
            print(f"{i:02d}. {sheet}")

        wb.close()

    except Exception as e:

        print("Workbook Open : FAIL ✗")
        print(f"Error : {e}")

# ------------------------------------------------
# Final status
# ------------------------------------------------

print("-" * 70)

if (
    final_excel_path.exists()
    and workbook_open_check
    and sheet_control
    and len(expected_sheets) == 16
):
    print("FINAL EXCEL FILE VALIDATION : PASS ✓")
else:
    print("FINAL EXCEL FILE VALIDATION : CHECK REQUIRED")

print("=" * 70)

======================================================================
PHASE 11 — PART 2 — CELL 3
FINAL EXCEL FILE VALIDATION
======================================================================
----------------------------------------------------------------------
FILE EXISTENCE CONTROL
----------------------------------------------------------------------
File Exists : PASS ✓
File Size   : 23,854 bytes
----------------------------------------------------------------------
WORKBOOK OPEN CONTROL
----------------------------------------------------------------------
Workbook Open : PASS ✓
Actual Sheets : 16
----------------------------------------------------------------------
SHEET CONTROL
----------------------------------------------------------------------
Sheet Names : PASS ✓
----------------------------------------------------------------------
FINAL SHEET LIST
----------------------------------------------------------------------
01. Customers_Master
02. Suppliers_Master
03. Sales_Transactions
04. Purchase_Transactions
05. Customer_Receipts
06. Supplier_Payments
07. Overpayment_Detail
08. Executive_Action_Plan
09. Management_Recommendations
10. Exec_Management_Summary
11. Executive_KPI_Control
12. Risk_Control
13. Executive_Decision
14. Final_Management_Rec
15. Final_Control
16. Output_Object_Control
----------------------------------------------------------------------
FINAL EXCEL FILE VALIDATION : PASS ✓
======================================================================

### Phase 11 Part 3 Cell 1:
### Download Final Excel

In [ ]:
# ================================================================
# PHASE 11 — PART 3 — CELL 1
# DOWNLOAD FINAL EXCEL
# ================================================================

from google.colab import files
from pathlib import Path

final_excel_path = Path(
    "/content/AR_AP_Analytics_Dashboard_FINAL.xlsx"
)

print("=" * 70)
print("PHASE 11 — PART 3 — CELL 1")
print("DOWNLOAD FINAL EXCEL")
print("=" * 70)

if final_excel_path.exists():

    print("-" * 70)
    print("FINAL EXCEL FILE READY")
    print("-" * 70)

    print(f"File Name : {final_excel_path.name}")
    print(f"File Size : {final_excel_path.stat().st_size:,} bytes")
    print("-" * 70)
    print("DOWNLOAD STARTING...")
    print("-" * 70)

    files.download(str(final_excel_path))

    print("FINAL EXCEL DOWNLOAD REQUEST SENT ✓")
    print("=" * 70)

else:

    print("ERROR: Final Excel file was not found.")
    print("=" * 70)

======================================================================
PHASE 11 — PART 3 — CELL 1
DOWNLOAD FINAL EXCEL
======================================================================
----------------------------------------------------------------------
FINAL EXCEL FILE READY
----------------------------------------------------------------------
File Name : AR_AP_Analytics_Dashboard_FINAL.xlsx
File Size : 23,854 bytes
----------------------------------------------------------------------
DOWNLOAD STARTING...
----------------------------------------------------------------------

FINAL EXCEL DOWNLOAD REQUEST SENT ✓
======================================================================

### Phase 11 Part 3 Cell 1:
### Final Project File Inventory

In [ ]:
# ================================================================
# PHASE 11 — PART 3 — CELL 1
# FINAL PROJECT FILE INVENTORY
# ================================================================

from pathlib import Path

print("=" * 70)
print("PHASE 11 — PART 3 — CELL 1")
print("FINAL PROJECT FILE INVENTORY")
print("=" * 70)

# ------------------------------------------------
# Expected project files
# ------------------------------------------------

project_files = {
    "Final Excel": Path(
        "/content/AR_AP_Analytics_Dashboard_FINAL.xlsx"
    ),
    "Final Notebook": Path(
        "/content/AR_AP_Analytics_Dashboard _Step_10.5_Part_11.ipynb"
    )
}

print("-" * 70)
print("PROJECT FILE CONTROL")
print("-" * 70)

available_files = 0
missing_files = 0

for file_type, file_path in project_files.items():

    if file_path.exists():

        available_files += 1

        print(
            f"{file_type:<20} : AVAILABLE ✓"
        )
        print(
            f"{'File Name':<20} : {file_path.name}"
        )
        print(
            f"{'File Size':<20} : {file_path.stat().st_size:,} bytes"
        )
        print("-" * 70)

    else:

        missing_files += 1

        print(
            f"{file_type:<20} : NOT FOUND"
        )
        print(
            f"{'Expected Path':<20} : {file_path}"
        )
        print("-" * 70)

print("FINAL FILE INVENTORY")
print("-" * 70)

print(f"Available Files : {available_files}")
print(f"Missing Files   : {missing_files}")

print("-" * 70)

if missing_files == 0:
    print("FINAL PROJECT FILE INVENTORY : PASS ✓")
else:
    print("FINAL PROJECT FILE INVENTORY : CHECK REQUIRED")

print("=" * 70)

======================================================================
PHASE 11 — PART 3 — CELL 1
FINAL PROJECT FILE INVENTORY
======================================================================
----------------------------------------------------------------------
PROJECT FILE CONTROL
----------------------------------------------------------------------
Final Excel          : AVAILABLE ✓
File Name            : AR_AP_Analytics_Dashboard_FINAL.xlsx
File Size            : 23,854 bytes
----------------------------------------------------------------------
Final Notebook       : NOT FOUND
Expected Path        : /content/AR_AP_Analytics_Dashboard _Step_10.5_Part_11.ipynb
----------------------------------------------------------------------
FINAL FILE INVENTORY
----------------------------------------------------------------------
Available Files : 1
Missing Files   : 1
----------------------------------------------------------------------
FINAL PROJECT FILE INVENTORY : CHECK REQUIRED
======================================================================

### Phase 11 Part 3 Cell 2:
### Upload & Validate Final Notebook

In [ ]:
# ================================================================
# PHASE 11 — PART 3 — CELL 2
# UPLOAD & VALIDATE FINAL NOTEBOOK
# ================================================================

from google.colab import files
from pathlib import Path

print("=" * 70)
print("PHASE 11 — PART 3 — CELL 2")
print("UPLOAD & VALIDATE FINAL NOTEBOOK")
print("=" * 70)

print("-" * 70)
print("PLEASE SELECT THE FINAL NOTEBOOK FROM YOUR COMPUTER")
print("-" * 70)

uploaded = files.upload()

print("-" * 70)
print("UPLOADED FILES")
print("-" * 70)

for filename, data in uploaded.items():
    print(f"{filename} : {len(data):,} bytes")

print("-" * 70)

notebook_files = [
    filename
    for filename in uploaded.keys()
    if filename.lower().endswith(".ipynb")
]

if len(notebook_files) == 1:

    notebook_name = notebook_files[0]
    notebook_path = Path("/content") / notebook_name

    print("Notebook Detected : PASS ✓")
    print(f"Notebook Name     : {notebook_name}")
    print(f"Notebook Size     : {notebook_path.stat().st_size:,} bytes")

    # Basic JSON validation
    import json

    try:
        with open(notebook_path, "r", encoding="utf-8") as f:
            notebook_data = json.load(f)

        required_keys = [
            "cells",
            "metadata",
            "nbformat"
        ]

        missing_keys = [
            key for key in required_keys
            if key not in notebook_data
        ]

        if not missing_keys:

            print("Notebook JSON Structure : PASS ✓")
            print(
                f"Notebook Cells          : "
                f"{len(notebook_data['cells'])}"
            )

            notebook_validation = True

        else:

            print("Notebook JSON Structure : CHECK")
            print(f"Missing Keys : {missing_keys}")

            notebook_validation = False

    except Exception as e:

        print("Notebook JSON Structure : FAIL ✗")
        print(f"Error : {e}")

        notebook_validation = False

else:

    print("Notebook Detection : CHECK REQUIRED")
    print(f"Detected .ipynb Files : {len(notebook_files)}")

    notebook_validation = False

print("-" * 70)

if notebook_validation:
    print("FINAL NOTEBOOK VALIDATION : PASS ✓")
else:
    print("FINAL NOTEBOOK VALIDATION : CHECK REQUIRED")

print("=" * 70)

======================================================================
PHASE 11 — PART 3 — CELL 2
UPLOAD & VALIDATE FINAL NOTEBOOK
======================================================================
----------------------------------------------------------------------
PLEASE SELECT THE FINAL NOTEBOOK FROM YOUR COMPUTER
----------------------------------------------------------------------

Saving AR_AP_Analytics_Dashboard_Step_10_05_Part_11.ipynb to AR_AP_Analytics_Dashboard_Step_10_05_Part_11.ipynb
----------------------------------------------------------------------
UPLOADED FILES
----------------------------------------------------------------------
AR_AP_Analytics_Dashboard_Step_10_05_Part_11.ipynb : 592,420 bytes
----------------------------------------------------------------------
Notebook Detected : PASS ✓
Notebook Name     : AR_AP_Analytics_Dashboard_Step_10_05_Part_11.ipynb
Notebook Size     : 592,420 bytes
Notebook JSON Structure : PASS ✓
Notebook Cells          : 71
----------------------------------------------------------------------
FINAL NOTEBOOK VALIDATION : PASS ✓
======================================================================

### Phase 11 Part 4 Cell 1:
### Final Project Packing Control

In [ ]:
# ======================================================================
# PHASE 11 — PART 4 — CELL 1
# FINAL PROJECT PACKAGING CONTROL
# ======================================================================

import os
from pathlib import Path

print("=" * 70)
print("PHASE 11 — PART 4 — CELL 1")
print("FINAL PROJECT PACKAGING CONTROL")
print("=" * 70)

# ----------------------------------------------------------------------
# PROJECT FILES
# ----------------------------------------------------------------------

project_files = {
    "Final Excel":
        "/content/AR_AP_Analytics_Dashboard_FINAL.xlsx",

    "Final Notebook":
        "/content/AR_AP_Analytics_Dashboard_Step_10_05_Part_11.ipynb"
}

print("-" * 70)
print("FINAL PROJECT FILE CONTROL")
print("-" * 70)

file_control = []

for file_type, file_path in project_files.items():

    exists = os.path.isfile(file_path)

    if exists:
        size = os.path.getsize(file_path)
        status = "AVAILABLE"
    else:
        size = 0
        status = "MISSING"

    file_control.append({
        "File Type": file_type,
        "File Name": os.path.basename(file_path),
        "File Size (Bytes)": size,
        "Status": status
    })

    print(f"{file_type:<20} : {status} ✓" if exists
          else f"{file_type:<20} : {status} ✗")

# ----------------------------------------------------------------------
# PACKAGING REQUIREMENTS
# ----------------------------------------------------------------------

required_files = [
    "Final Excel",
    "Final Notebook"
]

missing_files = [
    row["File Type"]
    for row in file_control
    if row["File Type"] in required_files
    and row["Status"] != "AVAILABLE"
]

available_files = [
    row["File Type"]
    for row in file_control
    if row["Status"] == "AVAILABLE"
]

print("-" * 70)
print("PACKAGING REQUIREMENT CONTROL")
print("-" * 70)

print(f"Required Project Files : {len(required_files)}")
print(f"Available Project Files: {len(available_files)}")
print(f"Missing Project Files  : {len(missing_files)}")

if missing_files:
    print("Missing Files:")
    for item in missing_files:
        print(f"  - {item}")

# ----------------------------------------------------------------------
# FINAL PACKAGING STATUS
# ----------------------------------------------------------------------

print("-" * 70)

if len(missing_files) == 0:
    packaging_status = "PASS"
else:
    packaging_status = "CHECK REQUIRED"

print(f"FINAL PACKAGING STATUS : {packaging_status}")

print("=" * 70)

if packaging_status == "PASS":
    print("PHASE 11 — PART 4 — CELL 1: COMPLETED ✓")
    print("FINAL PROJECT PACKAGING CONTROL: PASS ✓")
else:
    print("PHASE 11 — PART 4 — CELL 1: CHECK REQUIRED")

print("=" * 70)

======================================================================
PHASE 11 — PART 4 — CELL 1
FINAL PROJECT PACKAGING CONTROL
======================================================================
----------------------------------------------------------------------
FINAL PROJECT FILE CONTROL
----------------------------------------------------------------------
Final Excel          : AVAILABLE ✓
Final Notebook       : AVAILABLE ✓
----------------------------------------------------------------------
PACKAGING REQUIREMENT CONTROL
----------------------------------------------------------------------
Required Project Files : 2
Available Project Files: 2
Missing Project Files  : 0
----------------------------------------------------------------------
FINAL PACKAGING STATUS : PASS
======================================================================
PHASE 11 — PART 4 — CELL 1: COMPLETED ✓
FINAL PROJECT PACKAGING CONTROL: PASS ✓
======================================================================

### Phase 11 Part 4 Cell 2:
### Final Project Packing Creation

In [ ]:
# ======================================================================
# PHASE 11 — PART 4 — CELL 2
# FINAL PROJECT PACKAGE CREATION
# ======================================================================

import os
import zipfile

print("=" * 70)
print("PHASE 11 — PART 4 — CELL 2")
print("FINAL PROJECT PACKAGE CREATION")
print("=" * 70)

# ----------------------------------------------------------------------
# FILE PATHS
# ----------------------------------------------------------------------

excel_file = "/content/AR_AP_Analytics_Dashboard_FINAL.xlsx"

notebook_file = "/content/AR_AP_Analytics_Dashboard_Step_10_05_Part_11.ipynb"

package_file = "/content/AR_AP_Analytics_Dashboard_FINAL_PACKAGE.zip"

# ----------------------------------------------------------------------
# REQUIRED FILE CONTROL
# ----------------------------------------------------------------------

required_files = {
    "Final Excel": excel_file,
    "Final Notebook": notebook_file
}

print("-" * 70)
print("PACKAGE SOURCE FILE CONTROL")
print("-" * 70)

all_available = True

for label, file_path in required_files.items():
    if os.path.exists(file_path):
        size = os.path.getsize(file_path)
        print(f"{label:<20}: AVAILABLE ✓ | {size:,} bytes")
    else:
        print(f"{label:<20}: MISSING ✗")
        all_available = False

# ----------------------------------------------------------------------
# STOP IF ANY REQUIRED FILE IS MISSING
# ----------------------------------------------------------------------

if not all_available:
    raise FileNotFoundError(
        "One or more required project files are missing."
    )

# ----------------------------------------------------------------------
# CREATE FINAL ZIP PACKAGE
# ----------------------------------------------------------------------

print("-" * 70)
print("CREATING FINAL PROJECT PACKAGE")
print("-" * 70)

with zipfile.ZipFile(
    package_file,
    mode="w",
    compression=zipfile.ZIP_DEFLATED
) as zipf:

    zipf.write(
        excel_file,
        arcname="AR_AP_Analytics_Dashboard_FINAL.xlsx"
    )

    zipf.write(
        notebook_file,
        arcname="AR_AP_Analytics_Dashboard_Step_10_05_Part_11.ipynb"
    )

# ----------------------------------------------------------------------
# PACKAGE VALIDATION
# ----------------------------------------------------------------------

print("-" * 70)
print("FINAL PACKAGE VALIDATION")
print("-" * 70)

if not os.path.exists(package_file):
    raise FileNotFoundError(
        "Final package was not created."
    )

package_size = os.path.getsize(package_file)

with zipfile.ZipFile(package_file, "r") as zipf:
    package_contents = zipf.namelist()

expected_contents = [
    "AR_AP_Analytics_Dashboard_FINAL.xlsx",
    "AR_AP_Analytics_Dashboard_Step_10_05_Part_11.ipynb"
]

print(f"Package Exists       : PASS ✓")
print(f"Package Size         : {package_size:,} bytes")
print(f"Files Inside Package : {len(package_contents)}")

print("-" * 70)
print("PACKAGE CONTENT CONTROL")
print("-" * 70)

for filename in expected_contents:
    if filename in package_contents:
        print(f"{filename:<55}: PASS ✓")
    else:
        print(f"{filename:<55}: FAIL ✗")

# ----------------------------------------------------------------------
# FINAL STATUS
# ----------------------------------------------------------------------

package_control_pass = (
    len(package_contents) == 2
    and all(filename in package_contents for filename in expected_contents)
)

print("-" * 70)

if package_control_pass:
    print("PACKAGE CONTENT STATUS : PASS ✓")
    print("FINAL PROJECT PACKAGE  : READY ✓")
else:
    print("PACKAGE CONTENT STATUS : FAIL ✗")
    print("FINAL PROJECT PACKAGE  : CHECK REQUIRED")

print("=" * 70)
print("PHASE 11 — PART 4 — CELL 2: COMPLETED ✓")
print("=" * 70)

======================================================================
PHASE 11 — PART 4 — CELL 2
FINAL PROJECT PACKAGE CREATION
======================================================================
----------------------------------------------------------------------
PACKAGE SOURCE FILE CONTROL
----------------------------------------------------------------------
Final Excel         : AVAILABLE ✓ | 23,854 bytes
Final Notebook      : AVAILABLE ✓ | 592,420 bytes
----------------------------------------------------------------------
CREATING FINAL PROJECT PACKAGE
----------------------------------------------------------------------
----------------------------------------------------------------------
FINAL PACKAGE VALIDATION
----------------------------------------------------------------------
Package Exists       : PASS ✓
Package Size         : 74,187 bytes
Files Inside Package : 2
----------------------------------------------------------------------
PACKAGE CONTENT CONTROL
----------------------------------------------------------------------
AR_AP_Analytics_Dashboard_FINAL.xlsx                   : PASS ✓
AR_AP_Analytics_Dashboard_Step_10_05_Part_11.ipynb     : PASS ✓
----------------------------------------------------------------------
PACKAGE CONTENT STATUS : PASS ✓
FINAL PROJECT PACKAGE  : READY ✓
======================================================================
PHASE 11 — PART 4 — CELL 2: COMPLETED ✓
======================================================================

### Phase 11 Part 5: Final Package Export & Download Control

In [ ]:
# ======================================================================
# PHASE 11 — PART 5 — FINAL PACKAGE EXPORT & DOWNLOAD CONTROL
# ======================================================================

import os
from google.colab import files

print("=" * 70)
print("PHASE 11 — PART 5 — FINAL PACKAGE EXPORT & DOWNLOAD CONTROL")
print("=" * 70)

# ----------------------------------------------------------------------
# FINAL PACKAGE PATH
# ----------------------------------------------------------------------

package_path = "/content/AR_AP_Analytics_Dashboard_FINAL.zip"

print("-" * 70)
print("FINAL PACKAGE EXPORT CONTROL")
print("-" * 70)

# ----------------------------------------------------------------------
# FILE EXISTENCE CONTROL
# ----------------------------------------------------------------------

if not os.path.exists(package_path):
    raise FileNotFoundError(
        "Final project package was not found: "
        "AR_AP_Analytics_Dashboard_FINAL.zip"
    )

package_size = os.path.getsize(package_path)

print("Package File : AR_AP_Analytics_Dashboard_FINAL.zip")
print(f"Package Size : {package_size:,} bytes")
print("Package Exists : PASS ✓")

# ----------------------------------------------------------------------
# DOWNLOAD CONTROL
# ----------------------------------------------------------------------

print("-" * 70)
print("DOWNLOAD CONTROL")
print("-" * 70)

print("Starting final package download...")
files.download(package_path)

print("-" * 70)
print("FINAL PACKAGE EXPORT STATUS : PASS ✓")
print("FINAL PACKAGE DOWNLOAD : INITIATED ✓")
print("=" * 70)
print("PHASE 11 — PART 5: COMPLETED ✓")
print("=" * 70)

======================================================================
PHASE 11 — PART 5 — FINAL PACKAGE EXPORT & DOWNLOAD CONTROL
======================================================================
----------------------------------------------------------------------
FINAL PACKAGE EXPORT CONTROL
----------------------------------------------------------------------

FileNotFoundError: Final project package was not found: AR_AP_Analytics_Dashboard_FINAL.zip

### Phase 11 Part 5 Cell 1A
### Locate Final Project Package

In [ ]:
# ======================================================================
# PHASE 11 — PART 5 — CELL 1A
# LOCATE FINAL PROJECT PACKAGE
# ======================================================================

import os

print("=" * 70)
print("PHASE 11 — PART 5 — CELL 1A")
print("LOCATE FINAL PROJECT PACKAGE")
print("=" * 70)

print("-" * 70)
print("ZIP FILES FOUND IN /content")
print("-" * 70)

zip_files = []

for file_name in os.listdir("/content"):
    if file_name.lower().endswith(".zip"):
        full_path = os.path.join("/content", file_name)
        size = os.path.getsize(full_path)
        zip_files.append((file_name, size, full_path))

if len(zip_files) == 0:
    print("No ZIP files found.")
    print("PACKAGE SEARCH STATUS : NOT FOUND")
else:
    for name, size, path in zip_files:
        print(f"{name:<60} : {size:,} bytes")

    print("-" * 70)
    print(f"ZIP FILES FOUND : {len(zip_files)}")
    print("PACKAGE SEARCH STATUS : PASS ✓")

print("=" * 70)

======================================================================
PHASE 11 — PART 5 — CELL 1A
LOCATE FINAL PROJECT PACKAGE
======================================================================
----------------------------------------------------------------------
ZIP FILES FOUND IN /content
----------------------------------------------------------------------
AR_AP_Analytics_Dashboard_FINAL_PACKAGE.zip                  : 74,187 bytes
----------------------------------------------------------------------
ZIP FILES FOUND : 1
PACKAGE SEARCH STATUS : PASS ✓
======================================================================

### Phase 11 Part 5 Cell 1B
### Final Package Export & Download

In [ ]:
# ======================================================================
# PHASE 11 — PART 5 — CELL 1B
# FINAL PACKAGE EXPORT & DOWNLOAD
# ======================================================================

import os
from google.colab import files

print("=" * 70)
print("PHASE 11 — PART 5 — CELL 1B")
print("FINAL PACKAGE EXPORT & DOWNLOAD")
print("=" * 70)

# ----------------------------------------------------------------------
# FINAL PACKAGE
# ----------------------------------------------------------------------

package_path = "/content/AR_AP_Analytics_Dashboard_FINAL_PACKAGE.zip"
package_name = os.path.basename(package_path)

print("-" * 70)
print("FINAL PACKAGE CONTROL")
print("-" * 70)

# ----------------------------------------------------------------------
# EXISTENCE CONTROL
# ----------------------------------------------------------------------

if not os.path.exists(package_path):
    raise FileNotFoundError(
        f"Final package not found: {package_name}"
    )

package_size = os.path.getsize(package_path)

print(f"Package Name : {package_name}")
print(f"Package Size : {package_size:,} bytes")
print("Package Exists : PASS ✓")

# ----------------------------------------------------------------------
# DOWNLOAD
# ----------------------------------------------------------------------

print("-" * 70)
print("FINAL DOWNLOAD CONTROL")
print("-" * 70)

files.download(package_path)

print("Download Command : EXECUTED ✓")
print("-" * 70)
print("FINAL PACKAGE EXPORT STATUS : PASS ✓")
print("FINAL PACKAGE DOWNLOAD STATUS : PASS ✓")
print("=" * 70)
print("PHASE 11 — PART 5: COMPLETED ✓")
print("FINAL PROJECT PACKAGE: READY FOR PORTFOLIO / JOB PUBLISHING ✓")
print("=" * 70)

======================================================================
PHASE 11 — PART 5 — CELL 1B
FINAL PACKAGE EXPORT & DOWNLOAD
======================================================================
----------------------------------------------------------------------
FINAL PACKAGE CONTROL
----------------------------------------------------------------------
Package Name : AR_AP_Analytics_Dashboard_FINAL_PACKAGE.zip
Package Size : 74,187 bytes
Package Exists : PASS ✓
----------------------------------------------------------------------
FINAL DOWNLOAD CONTROL
----------------------------------------------------------------------

Download Command : EXECUTED ✓
----------------------------------------------------------------------
FINAL PACKAGE EXPORT STATUS : PASS ✓
FINAL PACKAGE DOWNLOAD STATUS : PASS ✓
======================================================================
PHASE 11 — PART 5: COMPLETED ✓
FINAL PROJECT PACKAGE: READY FOR PORTFOLIO / JOB PUBLISHING ✓
======================================================================